// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// AdjustmentRule condition for matching infoTypes.
public struct AdjustByMatchingInfoTypes: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Sensitive Data Protection adjusts the likelihood of a finding if that
  /// finding also matches one of these infoTypes.
  ///
  /// For example, you can create a rule to adjust the likelihood of a
  /// `PHONE_NUMBER` finding if the string is found within a document that is
  /// classified as `DOCUMENT_TYPE/HR/RESUME`. To configure this, set
  /// `PHONE_NUMBER` in `InspectionRuleSet.info_types`. Add an `adjustment_rule`
  /// with an `adjust_by_matching_info_types.info_types` that contains
  /// `DOCUMENT_TYPE/HR/RESUME`. In this case, the likelihood of the
  /// `PHONE_NUMBER` finding is adjusted, but the likelihood of the
  /// `DOCUMENT_TYPE/HR/RESUME` finding is not.
  public var infoTypes: [InfoType] = []

  /// Required. Minimum likelihood of the
  /// `adjust_by_matching_info_types.info_types` finding. If the likelihood is
  /// lower than this value, Sensitive Data Protection doesn't adjust the
  /// likelihood of the `InspectionRuleSet.info_types` finding.
  public var minLikelihood: Likelihood = Likelihood()

  /// How the adjustment rule is applied.
  ///
  /// Only `MATCHING_TYPE_PARTIAL_MATCH` is supported:
  ///
  /// - Partial match: adjusts the findings of infoTypes specified in the
  /// inspection rule when they have a nonempty intersection with a finding of an
  /// infoType specified in this adjustment rule.
  public var matchingType: MatchingType = MatchingType()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AdjustByMatchingInfoTypes`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AdjustByMatchingInfoTypes().with { $0.infoTypes = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let infoTypes = CodingKeys(stringValue: "infoTypes")
    static let minLikelihood = CodingKeys(stringValue: "minLikelihood")
    static let matchingType = CodingKeys(stringValue: "matchingType")

    static let _knownKeys: Set<Swift.String> = [
      "infoTypes",
      "minLikelihood",
      "matchingType",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent([InfoType].self, forKey: .infoTypes) {
      self.infoTypes = value
    }
    if let value = try container.decodeIfPresent(Likelihood.self, forKey: .minLikelihood) {
      self.minLikelihood = value
    }
    if let value = try container.decodeIfPresent(MatchingType.self, forKey: .matchingType) {
      self.matchingType = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.infoTypes, forKey: .infoTypes)
    try container.encode(self.minLikelihood, forKey: .minLikelihood)
    try container.encode(self.matchingType, forKey: .matchingType)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `AdjustByMatchingInfoTypes`: `"type.googleapis.com/google.privacy.dlp.v2.AdjustByMatchingInfoTypes"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.AdjustByMatchingInfoTypes"
  }

  /// Initialize an instance of `AdjustByMatchingInfoTypes` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.privacy.dlp.v2.AdjustByMatchingInfoTypes"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `AdjustByMatchingInfoTypes` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
