// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Options defining BigQuery table and row identifiers.
public struct BigQueryOptions: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Complete BigQuery table reference.
  public var tableReference: BigQueryTable? = nil

  /// Table fields that may uniquely identify a row within the table. When
  /// `actions.saveFindings.outputConfig.table` is specified, the values of
  /// columns specified here are available in the output table under
  /// `location.content_locations.record_location.record_key.id_values`. Nested
  /// fields such as `person.birthdate.year` are allowed.
  public var identifyingFields: [FieldId] = []

  /// Max number of rows to scan. If the table has more rows than this value, the
  /// rest of the rows are omitted. If not set, or if set to 0, all rows will be
  /// scanned. Only one of rows_limit and rows_limit_percent can be specified.
  /// Cannot be used in conjunction with TimespanConfig.
  public var rowsLimit: Swift.Int64 = Swift.Int64()

  /// Max percentage of rows to scan. The rest are omitted. The number of rows
  /// scanned is rounded down. Must be between 0 and 100, inclusively. Both 0 and
  /// 100 means no limit. Defaults to 0. Only one of rows_limit and
  /// rows_limit_percent can be specified. Cannot be used in conjunction with
  /// TimespanConfig.
  ///
  /// Caution: A [known
  /// issue](https://docs.cloud.google.com/sensitive-data-protection/docs/known-issues#bq-sampling)
  /// is causing the `rowsLimitPercent` field to behave unexpectedly. We
  /// recommend using `rowsLimit` instead.
  public var rowsLimitPercent: Swift.Int32 = Swift.Int32()

  /// How to sample the data.
  public var sampleMethod: BigQueryOptions.SampleMethod = BigQueryOptions.SampleMethod()

  /// References to fields excluded from scanning. This allows you to skip
  /// inspection of entire columns which you know have no findings.
  /// When inspecting a table, we recommend that you inspect all columns.
  /// Otherwise, findings might be affected because hints from excluded columns
  /// will not be used.
  public var excludedFields: [FieldId] = []

  /// Limit scanning only to these fields.
  /// When inspecting a table, we recommend that you inspect all columns.
  /// Otherwise, findings might be affected because hints from excluded columns
  /// will not be used.
  public var includedFields: [FieldId] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `BigQueryOptions`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BigQueryOptions().with { $0.tableReference = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let tableReference = CodingKeys(stringValue: "tableReference")
    static let identifyingFields = CodingKeys(stringValue: "identifyingFields")
    static let rowsLimit = CodingKeys(stringValue: "rowsLimit")
    static let rowsLimitPercent = CodingKeys(stringValue: "rowsLimitPercent")
    static let sampleMethod = CodingKeys(stringValue: "sampleMethod")
    static let excludedFields = CodingKeys(stringValue: "excludedFields")
    static let includedFields = CodingKeys(stringValue: "includedFields")

    static let _knownKeys: Set<Swift.String> = [
      "tableReference",
      "identifyingFields",
      "rowsLimit",
      "rowsLimitPercent",
      "sampleMethod",
      "excludedFields",
      "includedFields",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.tableReference = try container.decodeIfPresent(BigQueryTable.self, forKey: .tableReference)
    if let value = try container.decodeIfPresent([FieldId].self, forKey: .identifyingFields) {
      self.identifyingFields = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .rowsLimit) {
      self.rowsLimit = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .rowsLimitPercent) {
      self.rowsLimitPercent = value
    }
    if let value = try container.decodeIfPresent(
      BigQueryOptions.SampleMethod.self, forKey: .sampleMethod)
    {
      self.sampleMethod = value
    }
    if let value = try container.decodeIfPresent([FieldId].self, forKey: .excludedFields) {
      self.excludedFields = value
    }
    if let value = try container.decodeIfPresent([FieldId].self, forKey: .includedFields) {
      self.includedFields = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.tableReference, forKey: .tableReference)
    try container.encode(self.identifyingFields, forKey: .identifyingFields)
    try container.encode(self.rowsLimit, forKey: .rowsLimit)
    try container.encode(self.rowsLimitPercent, forKey: .rowsLimitPercent)
    try container.encode(self.sampleMethod, forKey: .sampleMethod)
    try container.encode(self.excludedFields, forKey: .excludedFields)
    try container.encode(self.includedFields, forKey: .includedFields)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// How to sample rows if not all rows are scanned. Meaningful only when used
  /// in conjunction with either rows_limit or rows_limit_percent. If not
  /// specified, rows are scanned in the order BigQuery reads them.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum SampleMethod: Codable, Equatable, Hashable, Sendable {
    /// No sampling.
    case unspecified
    /// Scan groups of rows in the order BigQuery provides (default). Multiple
    /// groups of rows may be scanned in parallel, so results may not appear in
    /// the same order the rows are read.
    case top
    /// Randomly pick groups of rows to scan.
    case randomStart
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .top: return 1
      case .randomStart: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "SAMPLE_METHOD_UNSPECIFIED"
      case .top: return "TOP"
      case .randomStart: return "RANDOM_START"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:SampleMethod/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "SAMPLE_METHOD_UNSPECIFIED": self = .unspecified
      case "TOP": self = .top
      case "RANDOM_START": self = .randomStart
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:SampleMethod/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .top
      case 2: self = .randomStart
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("SAMPLE_METHOD_UNSPECIFIED")
      case .top: return try container.encode("TOP")
      case .randomStart: return try container.encode("RANDOM_START")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The type URL for `BigQueryOptions`: `"type.googleapis.com/google.privacy.dlp.v2.BigQueryOptions"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.BigQueryOptions"
  }

  /// Initialize an instance of `BigQueryOptions` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.privacy.dlp.v2.BigQueryOptions"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `BigQueryOptions` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
