// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// State of the connection.
/// New values may be added over time.
///
/// - Note: Adding cases to this enumeration is not considered a breaking change.
///   Always include an `@unknown default:` case when switching over this type.
///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
///   expecting specific values to remain unparsed; future releases may promote
///   them to named cases.
public enum ConnectionState: Codable, Equatable, Hashable, Sendable {
  /// Unused
  case unspecified
  /// The DLP API automatically created this connection during an initial scan,
  /// and it is awaiting full configuration by a user.
  case missingCredentials
  /// A configured connection that has not encountered any errors.
  case available
  /// A configured connection that encountered errors during its last use. It
  /// will not be used again until it is set to AVAILABLE.
  ///
  /// If the resolution requires external action, then the client must send a
  /// request to set the status to AVAILABLE when the connection is ready for
  /// use. If the resolution doesn't require external action, then any changes to
  /// the connection properties will automatically mark it as AVAILABLE.
  case error
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown value is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  ///
  /// - Warning: Do not pattern-match specific integer values in this case;
  ///   future releases may promote them to named enum cases.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown value is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  ///
  /// - Warning: Do not pattern-match specific string literals in this case;
  ///   future releases may promote them to named enum cases.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .missingCredentials: return 1
    case .available: return 2
    case .error: return 3
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "CONNECTION_STATE_UNSPECIFIED"
    case .missingCredentials: return "MISSING_CREDENTIALS"
    case .available: return "AVAILABLE"
    case .error: return "ERROR"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ConnectionState/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "CONNECTION_STATE_UNSPECIFIED": self = .unspecified
    case "MISSING_CREDENTIALS": self = .missingCredentials
    case "AVAILABLE": self = .available
    case "ERROR": self = .error
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ConnectionState/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .missingCredentials
    case 2: self = .available
    case 3: self = .error
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode("CONNECTION_STATE_UNSPECIFIED")
    case .missingCredentials: return try container.encode("MISSING_CREDENTIALS")
    case .available: return try container.encode("AVAILABLE")
    case .error: return try container.encode("ERROR")
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
