// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Represents a container that may contain DLP findings.
/// Examples of a container include a file, table, or database record.
public struct Container: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Container type, for example BigQuery or Cloud Storage.
  public var type: Swift.String = Swift.String()

  /// Project where the finding was found.
  /// Can be different from the project that owns the finding.
  public var projectId: Swift.String = Swift.String()

  /// A string representation of the full container name.
  /// Examples:
  /// - BigQuery: 'Project:DataSetId.TableId'
  /// - Cloud Storage: 'gs://Bucket/folders/filename.txt'
  public var fullPath: Swift.String = Swift.String()

  /// The root of the container.
  /// Examples:
  ///
  /// - For BigQuery table `project_id:dataset_id.table_id`, the root is
  ///  `dataset_id`
  /// - For Cloud Storage file `gs://bucket/folder/filename.txt`, the root
  ///  is `gs://bucket`
  public var rootPath: Swift.String = Swift.String()

  /// The rest of the path after the root.
  /// Examples:
  ///
  /// - For BigQuery table `project_id:dataset_id.table_id`, the relative path is
  ///  `table_id`
  /// - For Cloud Storage file `gs://bucket/folder/filename.txt`, the relative
  ///  path is `folder/filename.txt`
  public var relativePath: Swift.String = Swift.String()

  /// Findings container modification timestamp, if applicable. For Cloud
  /// Storage, this field contains the last file modification timestamp. For a
  /// BigQuery table, this field contains the last_modified_time property. For
  /// Datastore, this field isn't populated.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Findings container version, if available
  /// ("generation" for Cloud Storage).
  public var version: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Container`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Container().with { $0.type = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let type = CodingKeys(stringValue: "type")
    static let projectId = CodingKeys(stringValue: "projectId")
    static let fullPath = CodingKeys(stringValue: "fullPath")
    static let rootPath = CodingKeys(stringValue: "rootPath")
    static let relativePath = CodingKeys(stringValue: "relativePath")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let version = CodingKeys(stringValue: "version")

    static let _knownKeys: Set<Swift.String> = [
      "type",
      "projectId",
      "fullPath",
      "rootPath",
      "relativePath",
      "updateTime",
      "version",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .type) {
      self.type = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .projectId) {
      self.projectId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .fullPath) {
      self.fullPath = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .rootPath) {
      self.rootPath = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .relativePath) {
      self.relativePath = value
    }
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .version) {
      self.version = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.type, forKey: .type)
    try container.encode(self.projectId, forKey: .projectId)
    try container.encode(self.fullPath, forKey: .fullPath)
    try container.encode(self.rootPath, forKey: .rootPath)
    try container.encode(self.relativePath, forKey: .relativePath)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.version, forKey: .version)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `Container`: `"type.googleapis.com/google.privacy.dlp.v2.Container"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.Container"
  }

  /// Initialize an instance of `Container` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.privacy.dlp.v2.Container"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `Container` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
