// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// Deprecated and unused.
///
/// - Note: Adding cases to this enumeration is not considered a breaking change.
///   Always include an `@unknown default:` case when switching over this type.
///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
///   expecting specific values to remain unparsed; future releases may promote
///   them to named cases.
public enum ContentOption: Codable, Equatable, Hashable, Sendable {
  /// Includes entire content of a file or a data stream.
  case contentUnspecified
  /// Text content within the data, excluding any metadata.
  case contentText
  /// Images found in the data.
  case contentImage
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown value is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  ///
  /// - Warning: Do not pattern-match specific integer values in this case;
  ///   future releases may promote them to named enum cases.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown value is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  ///
  /// - Warning: Do not pattern-match specific string literals in this case;
  ///   future releases may promote them to named enum cases.
  case unknownStringValue(String)

  public init() {
    self = .contentUnspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .contentUnspecified: return 0
    case .contentText: return 1
    case .contentImage: return 2
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .contentUnspecified: return "CONTENT_UNSPECIFIED"
    case .contentText: return "CONTENT_TEXT"
    case .contentImage: return "CONTENT_IMAGE"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ContentOption/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "CONTENT_UNSPECIFIED": self = .contentUnspecified
    case "CONTENT_TEXT": self = .contentText
    case "CONTENT_IMAGE": self = .contentImage
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ContentOption/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .contentUnspecified
    case 1: self = .contentText
    case 2: self = .contentImage
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .contentUnspecified: return try container.encode("CONTENT_UNSPECIFIED")
    case .contentText: return try container.encode("CONTENT_TEXT")
    case .contentImage: return try container.encode("CONTENT_IMAGE")
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
