// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request message for CreateStoredInfoType.
public struct CreateStoredInfoTypeRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Parent resource name.
  ///
  /// The format of this value varies depending on the scope of the request
  /// (project or organization) and whether you have [specified a processing
  /// location](https://docs.cloud.google.com/sensitive-data-protection/docs/specifying-location):
  ///
  /// + Projects scope, location specified:
  ///   `projects/{project_id}/locations/{location_id}`
  /// + Projects scope, no location specified (defaults to global):
  ///   `projects/{project_id}`
  /// + Organizations scope, location specified:
  ///   `organizations/{org_id}/locations/{location_id}`
  /// + Organizations scope, no location specified (defaults to global):
  ///   `organizations/{org_id}`
  ///
  /// The following example `parent` string specifies a parent project with the
  /// identifier `example-project`, and specifies the `europe-west3` location
  /// for processing data:
  ///
  ///     parent=projects/example-project/locations/europe-west3
  public var parent: Swift.String = Swift.String()

  /// Required. Configuration of the storedInfoType to create.
  public var config: StoredInfoTypeConfig? = nil

  /// The storedInfoType ID can contain uppercase and lowercase letters,
  /// numbers, and hyphens; that is, it must match the regular
  /// expression: `[a-zA-Z\d-_]+`. The maximum length is 100
  /// characters. Can be empty to allow the system to generate one.
  public var storedInfoTypeId: Swift.String = Swift.String()

  /// Deprecated. This field has no effect.
  public var locationId: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CreateStoredInfoTypeRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateStoredInfoTypeRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let config = CodingKeys(stringValue: "config")
    static let storedInfoTypeId = CodingKeys(stringValue: "storedInfoTypeId")
    static let locationId = CodingKeys(stringValue: "locationId")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "config",
      "storedInfoTypeId",
      "locationId",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    self.config = try container.decodeIfPresent(StoredInfoTypeConfig.self, forKey: .config)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .storedInfoTypeId) {
      self.storedInfoTypeId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .locationId) {
      self.locationId = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encodeIfPresent(self.config, forKey: .config)
    try container.encode(self.storedInfoTypeId, forKey: .storedInfoTypeId)
    try container.encode(self.locationId, forKey: .locationId)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.CreateStoredInfoTypeRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
