// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Replaces an identifier with a surrogate using Format Preserving Encryption
/// (FPE) with the FFX mode of operation; however when used in the
/// `ReidentifyContent` API method, it serves the opposite function by reversing
/// the surrogate back into the original identifier. The identifier must be
/// encoded as ASCII. For a given crypto key and context, the same identifier
/// will be replaced with the same surrogate. Identifiers must be at least two
/// characters long. In the case that the identifier is the empty string, it will
/// be skipped. See
/// https://docs.cloud.google.com/sensitive-data-protection/docs/pseudonymization
/// to learn more.
///
/// Note: We recommend using  CryptoDeterministicConfig for all use cases which
/// do not require preserving the input alphabet space and size, plus warrant
/// referential integrity. FPE incurs significant latency costs.
public struct CryptoReplaceFfxFpeConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The key used by the encryption algorithm.
  public var cryptoKey: CryptoKey? = nil

  /// The 'tweak', a context may be used for higher security since the same
  /// identifier in two different contexts won't be given the same surrogate. If
  /// the context is not set, a default tweak will be used.
  ///
  /// If the context is set but:
  ///
  /// 1. there is no record present when transforming a given value or
  /// 1. the field is not present when transforming a given value,
  ///
  /// a default tweak will be used.
  ///
  /// Note that case (1) is expected when an `InfoTypeTransformation` is
  /// applied to both structured and unstructured `ContentItem`s.
  /// Currently, the referenced field may be of value type integer or string.
  ///
  /// The tweak is constructed as a sequence of bytes in big endian byte order
  /// such that:
  ///
  /// - a 64 bit integer is encoded followed by a single byte of value 1
  /// - a string is encoded in UTF-8 format followed by a single byte of value 2
  public var context: FieldId? = nil

  /// The custom infoType to annotate the surrogate with.
  /// This annotation will be applied to the surrogate by prefixing it with
  /// the name of the custom infoType followed by the number of
  /// characters comprising the surrogate. The following scheme defines the
  /// format: info_type_name(surrogate_character_count):surrogate
  ///
  /// For example, if the name of custom infoType is 'MY_TOKEN_INFO_TYPE' and
  /// the surrogate is 'abc', the full replacement value
  /// will be: 'MY_TOKEN_INFO_TYPE(3):abc'
  ///
  /// This annotation identifies the surrogate when inspecting content using the
  /// custom infoType
  /// [`SurrogateType`](https://docs.cloud.google.com/sensitive-data-protection/docs/reference/rest/v2/InspectConfig#surrogatetype).
  /// This facilitates reversal of the surrogate when it occurs in free text.
  ///
  /// In order for inspection to work properly, the name of this infoType must
  /// not occur naturally anywhere in your data; otherwise, inspection may
  /// find a surrogate that does not correspond to an actual identifier.
  /// Therefore, choose your custom infoType name carefully after considering
  /// what your data looks like. One way to select a name that has a high chance
  /// of yielding reliable detection is to include one or more unicode characters
  /// that are highly improbable to exist in your data.
  /// For example, assuming your data is entered from a regular ASCII keyboard,
  /// the symbol with the hex code point 29DD might be used like so:
  /// ⧝MY_TOKEN_TYPE
  public var surrogateInfoType: InfoType? = nil

  /// Choose an alphabet which the data being transformed will be made up of.
  public var alphabet: AlphabetOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CryptoReplaceFfxFpeConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CryptoReplaceFfxFpeConfig().with { $0.cryptoKey = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let cryptoKey = CodingKeys(stringValue: "cryptoKey")
    static let context = CodingKeys(stringValue: "context")
    static let commonAlphabet = CodingKeys(stringValue: "commonAlphabet")
    static let customAlphabet = CodingKeys(stringValue: "customAlphabet")
    static let radix = CodingKeys(stringValue: "radix")
    static let surrogateInfoType = CodingKeys(stringValue: "surrogateInfoType")

    static let _knownKeys: Set<Swift.String> = [
      "cryptoKey",
      "context",
      "commonAlphabet",
      "customAlphabet",
      "radix",
      "surrogateInfoType",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.cryptoKey = try container.decodeIfPresent(CryptoKey.self, forKey: .cryptoKey)
    self.context = try container.decodeIfPresent(FieldId.self, forKey: .context)
    self.surrogateInfoType = try container.decodeIfPresent(
      InfoType.self, forKey: .surrogateInfoType)

    var alphabet: AlphabetOneOf? = nil
    let alphabetCheckAndSet = {
      if alphabet != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'alphabet'"))
      }
      alphabet = $0
    }
    if let commonAlphabet = try container.decodeIfPresent(
      CryptoReplaceFfxFpeConfig.FfxCommonNativeAlphabet.self, forKey: .commonAlphabet)
    {
      try alphabetCheckAndSet(.commonAlphabet(commonAlphabet))
    }
    if let customAlphabet = try container.decodeIfPresent(
      Swift.String.self, forKey: .customAlphabet)
    {
      try alphabetCheckAndSet(.customAlphabet(customAlphabet))
    }
    if let radix = try container.decodeIfPresent(Swift.Int32.self, forKey: .radix) {
      try alphabetCheckAndSet(.radix(radix))
    }
    self.alphabet = alphabet
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.cryptoKey, forKey: .cryptoKey)
    try container.encodeIfPresent(self.context, forKey: .context)
    try container.encodeIfPresent(self.surrogateInfoType, forKey: .surrogateInfoType)

    if let choice = self.alphabet {
      switch choice {
      case .commonAlphabet(let value):
        try container.encode(value, forKey: .commonAlphabet)
      case .customAlphabet(let value):
        try container.encode(value, forKey: .customAlphabet)
      case .radix(let value):
        try container.encode(value, forKey: .radix)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// These are commonly used subsets of the alphabet that the FFX mode
  /// natively supports. In the algorithm, the alphabet is selected using
  /// the "radix". Therefore each corresponds to a particular radix.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum FfxCommonNativeAlphabet: Codable, Equatable, Hashable, Sendable {
    /// Unused.
    case unspecified
    /// `[0-9]` (radix of 10)
    case numeric
    /// `[0-9A-F]` (radix of 16)
    case hexadecimal
    /// `[0-9A-Z]` (radix of 36)
    case upperCaseAlphaNumeric
    /// `[0-9A-Za-z]` (radix of 62)
    case alphaNumeric
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .numeric: return 1
      case .hexadecimal: return 2
      case .upperCaseAlphaNumeric: return 3
      case .alphaNumeric: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "FFX_COMMON_NATIVE_ALPHABET_UNSPECIFIED"
      case .numeric: return "NUMERIC"
      case .hexadecimal: return "HEXADECIMAL"
      case .upperCaseAlphaNumeric: return "UPPER_CASE_ALPHA_NUMERIC"
      case .alphaNumeric: return "ALPHA_NUMERIC"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:FfxCommonNativeAlphabet/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "FFX_COMMON_NATIVE_ALPHABET_UNSPECIFIED": self = .unspecified
      case "NUMERIC": self = .numeric
      case "HEXADECIMAL": self = .hexadecimal
      case "UPPER_CASE_ALPHA_NUMERIC": self = .upperCaseAlphaNumeric
      case "ALPHA_NUMERIC": self = .alphaNumeric
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:FfxCommonNativeAlphabet/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .numeric
      case 2: self = .hexadecimal
      case 3: self = .upperCaseAlphaNumeric
      case 4: self = .alphaNumeric
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("FFX_COMMON_NATIVE_ALPHABET_UNSPECIFIED")
      case .numeric: return try container.encode("NUMERIC")
      case .hexadecimal: return try container.encode("HEXADECIMAL")
      case .upperCaseAlphaNumeric: return try container.encode("UPPER_CASE_ALPHA_NUMERIC")
      case .alphaNumeric: return try container.encode("ALPHA_NUMERIC")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Choose an alphabet which the data being transformed will be made up of.
  public enum AlphabetOneOf: Codable, Equatable, Sendable {
    /// Common alphabets.
    case commonAlphabet(CryptoReplaceFfxFpeConfig.FfxCommonNativeAlphabet)
    /// This is supported by mapping these to the alphanumeric characters
    /// that the FFX mode natively supports. This happens before/after
    /// encryption/decryption.
    /// Each character listed must appear only once.
    /// Number of characters must be in the range [2, 95].
    /// This must be encoded as ASCII.
    /// The order of characters does not matter.
    /// The full list of allowed characters is:
    /// ``0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz~`!@#$%^&*()_-+={[}]|\:;"'<,>.?/``
    case customAlphabet(Swift.String)
    /// The native way to select the alphabet. Must be in the range [2, 95].
    case radix(Swift.Int32)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.CryptoReplaceFfxFpeConfig"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
