// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Snapshot of the configurations used to generate the profile.
public struct DataProfileConfigSnapshot: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// A copy of the inspection config used to generate this profile. This
  /// is a copy of the inspect_template specified in `DataProfileJobConfig`.
  public var inspectConfig: InspectConfig? = nil

  /// A copy of the configuration used to generate this profile. This is
  /// deprecated, and the DiscoveryConfig field is preferred moving forward.
  /// DataProfileJobConfig will still be written here for Discovery in BigQuery
  /// for backwards compatibility, but will not be updated with new fields, while
  /// DiscoveryConfig will.
  @available(*, deprecated)
  public var dataProfileJob: DataProfileJobConfig? = nil

  /// A copy of the configuration used to generate this profile.
  public var discoveryConfig: DiscoveryConfig? = nil

  /// Name of the inspection template used to generate this profile
  public var inspectTemplateName: Swift.String = Swift.String()

  /// Timestamp when the template was modified
  public var inspectTemplateModifiedTime: GoogleWKT.WKTTimestamp? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `DataProfileConfigSnapshot`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DataProfileConfigSnapshot().with { $0.inspectConfig = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let inspectConfig = CodingKeys(stringValue: "inspectConfig")
    static let dataProfileJob = CodingKeys(stringValue: "dataProfileJob")
    static let discoveryConfig = CodingKeys(stringValue: "discoveryConfig")
    static let inspectTemplateName = CodingKeys(stringValue: "inspectTemplateName")
    static let inspectTemplateModifiedTime = CodingKeys(stringValue: "inspectTemplateModifiedTime")

    static let _knownKeys: Set<Swift.String> = [
      "inspectConfig",
      "dataProfileJob",
      "discoveryConfig",
      "inspectTemplateName",
      "inspectTemplateModifiedTime",
    ]
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.inspectConfig = try container.decodeIfPresent(InspectConfig.self, forKey: .inspectConfig)
    self.dataProfileJob = try container.decodeIfPresent(
      DataProfileJobConfig.self, forKey: .dataProfileJob)
    self.discoveryConfig = try container.decodeIfPresent(
      DiscoveryConfig.self, forKey: .discoveryConfig)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .inspectTemplateName) {
      self.inspectTemplateName = value
    }
    self.inspectTemplateModifiedTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .inspectTemplateModifiedTime)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.inspectConfig, forKey: .inspectConfig)
    try container.encodeIfPresent(self.dataProfileJob, forKey: .dataProfileJob)
    try container.encodeIfPresent(self.discoveryConfig, forKey: .discoveryConfig)
    try container.encode(self.inspectTemplateName, forKey: .inspectTemplateName)
    try container.encodeIfPresent(
      self.inspectTemplateModifiedTime, forKey: .inspectTemplateModifiedTime)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `DataProfileConfigSnapshot`: `"type.googleapis.com/google.privacy.dlp.v2.DataProfileConfigSnapshot"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.DataProfileConfigSnapshot"
  }

  /// Initialize an instance of `DataProfileConfigSnapshot` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.privacy.dlp.v2.DataProfileConfigSnapshot"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `DataProfileConfigSnapshot` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
