// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Score is a summary of all elements in the data profile.
/// A higher number means more risk.
public struct DataRiskLevel: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The score applied to the resource.
  public var score: DataRiskLevel.DataRiskLevelScore = DataRiskLevel.DataRiskLevelScore()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `DataRiskLevel`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DataRiskLevel().with { $0.score = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let score = CodingKeys(stringValue: "score")

    static let _knownKeys: Set<Swift.String> = [
      "score"
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      DataRiskLevel.DataRiskLevelScore.self, forKey: .score)
    {
      self.score = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.score, forKey: .score)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Various score levels for resources.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum DataRiskLevelScore: Codable, Equatable, Hashable, Sendable {
    /// Unused.
    case riskScoreUnspecified
    /// Low risk - Lower indication of sensitive data that appears to have
    /// additional access restrictions in place or no indication of sensitive
    /// data found.
    case riskLow
    /// Unable to determine risk.
    case riskUnknown
    /// Medium risk - Sensitive data may be present but additional access or fine
    /// grain access restrictions appear to be present.  Consider limiting
    /// access even further or transform data to mask.
    case riskModerate
    /// High risk – SPII may be present. Access controls may include public
    /// ACLs. Exfiltration of data may lead to user data loss. Re-identification
    /// of users may be possible. Consider limiting usage and or removing SPII.
    case riskHigh
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .riskScoreUnspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .riskScoreUnspecified: return 0
      case .riskLow: return 10
      case .riskUnknown: return 12
      case .riskModerate: return 20
      case .riskHigh: return 30
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .riskScoreUnspecified: return "RISK_SCORE_UNSPECIFIED"
      case .riskLow: return "RISK_LOW"
      case .riskUnknown: return "RISK_UNKNOWN"
      case .riskModerate: return "RISK_MODERATE"
      case .riskHigh: return "RISK_HIGH"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:DataRiskLevelScore/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "RISK_SCORE_UNSPECIFIED": self = .riskScoreUnspecified
      case "RISK_LOW": self = .riskLow
      case "RISK_UNKNOWN": self = .riskUnknown
      case "RISK_MODERATE": self = .riskModerate
      case "RISK_HIGH": self = .riskHigh
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:DataRiskLevelScore/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .riskScoreUnspecified
      case 10: self = .riskLow
      case 12: self = .riskUnknown
      case 20: self = .riskModerate
      case 30: self = .riskHigh
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .riskScoreUnspecified: return try container.encode("RISK_SCORE_UNSPECIFIED")
      case .riskLow: return try container.encode("RISK_LOW")
      case .riskUnknown: return try container.encode("RISK_UNKNOWN")
      case .riskModerate: return try container.encode("RISK_MODERATE")
      case .riskHigh: return try container.encode("RISK_HIGH")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The type URL for `DataRiskLevel`: `"type.googleapis.com/google.privacy.dlp.v2.DataRiskLevel"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.DataRiskLevel"
  }

  /// Initialize an instance of `DataRiskLevel` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.privacy.dlp.v2.DataRiskLevel"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `DataRiskLevel` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
