// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Shifts dates by random number of days, with option to be consistent for the
/// same context. See
/// https://docs.cloud.google.com/sensitive-data-protection/docs/concepts-date-shifting
/// to learn more.
public struct DateShiftConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Range of shift in days. Actual shift will be selected at random
  /// within this range (inclusive ends). Negative means shift to earlier in
  /// time. Must not be more than 365250 days (1000 years) each direction.
  ///
  /// For example, 3 means shift date to at most 3 days into the future.
  public var upperBoundDays: Swift.Int32 = Swift.Int32()

  /// Required. For example, -5 means shift date to at most 5 days back in the
  /// past.
  public var lowerBoundDays: Swift.Int32 = Swift.Int32()

  /// Points to the field that contains the context, for example, an entity id.
  /// If set, must also set cryptoKey. If set, shift will be consistent for the
  /// given context.
  public var context: FieldId? = nil

  /// Method for calculating shift that takes context into consideration. If
  /// set, must also set context. Can only be applied to table items.
  public var method: MethodOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `DateShiftConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DateShiftConfig().with { $0.upperBoundDays = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let upperBoundDays = CodingKeys(stringValue: "upperBoundDays")
    static let lowerBoundDays = CodingKeys(stringValue: "lowerBoundDays")
    static let context = CodingKeys(stringValue: "context")
    static let cryptoKey = CodingKeys(stringValue: "cryptoKey")

    static let _knownKeys: Set<Swift.String> = [
      "upperBoundDays",
      "lowerBoundDays",
      "context",
      "cryptoKey",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .upperBoundDays) {
      self.upperBoundDays = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .lowerBoundDays) {
      self.lowerBoundDays = value
    }
    self.context = try container.decodeIfPresent(FieldId.self, forKey: .context)

    var method: MethodOneOf? = nil
    let methodCheckAndSet = {
      if method != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'method'"))
      }
      method = $0
    }
    if let cryptoKey = try container.decodeIfPresent(CryptoKey.self, forKey: .cryptoKey) {
      try methodCheckAndSet(.cryptoKey(cryptoKey))
    }
    self.method = method
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.upperBoundDays, forKey: .upperBoundDays)
    try container.encode(self.lowerBoundDays, forKey: .lowerBoundDays)
    try container.encodeIfPresent(self.context, forKey: .context)

    if let choice = self.method {
      switch choice {
      case .cryptoKey(let value):
        try container.encode(value, forKey: .cryptoKey)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Method for calculating shift that takes context into consideration. If
  /// set, must also set context. Can only be applied to table items.
  public enum MethodOneOf: Codable, Equatable, Sendable {
    /// Causes the shift to be computed based on this key and the context. This
    /// results in the same shift for the same context and crypto_key. If
    /// set, must also set context. Can only be applied to table items.
    indirect case cryptoKey(CryptoKey)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.DateShiftConfig"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
