// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The configuration that controls how the data will change.
public struct DeidentifyConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Mode for handling transformation errors. If left unspecified, the default
  /// mode is `TransformationErrorHandling.ThrowError`.
  public var transformationErrorHandling: TransformationErrorHandling? = nil

  /// Type of transformation
  public var transformation: TransformationOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `DeidentifyConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DeidentifyConfig().with { $0.infoTypeTransformations = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let infoTypeTransformations = CodingKeys(stringValue: "infoTypeTransformations")
    static let recordTransformations = CodingKeys(stringValue: "recordTransformations")
    static let imageTransformations = CodingKeys(stringValue: "imageTransformations")
    static let transformationErrorHandling = CodingKeys(stringValue: "transformationErrorHandling")

    static let _knownKeys: Set<Swift.String> = [
      "infoTypeTransformations",
      "recordTransformations",
      "imageTransformations",
      "transformationErrorHandling",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.transformationErrorHandling = try container.decodeIfPresent(
      TransformationErrorHandling.self, forKey: .transformationErrorHandling)

    var transformation: TransformationOneOf? = nil
    let transformationCheckAndSet = {
      if transformation != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'transformation'"))
      }
      transformation = $0
    }
    if let infoTypeTransformations = try container.decodeIfPresent(
      InfoTypeTransformations.self, forKey: .infoTypeTransformations)
    {
      try transformationCheckAndSet(.infoTypeTransformations(infoTypeTransformations))
    }
    if let recordTransformations = try container.decodeIfPresent(
      RecordTransformations.self, forKey: .recordTransformations)
    {
      try transformationCheckAndSet(.recordTransformations(recordTransformations))
    }
    if let imageTransformations = try container.decodeIfPresent(
      ImageTransformations.self, forKey: .imageTransformations)
    {
      try transformationCheckAndSet(.imageTransformations(imageTransformations))
    }
    self.transformation = transformation
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(
      self.transformationErrorHandling, forKey: .transformationErrorHandling)

    if let choice = self.transformation {
      switch choice {
      case .infoTypeTransformations(let value):
        try container.encode(value, forKey: .infoTypeTransformations)
      case .recordTransformations(let value):
        try container.encode(value, forKey: .recordTransformations)
      case .imageTransformations(let value):
        try container.encode(value, forKey: .imageTransformations)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Type of transformation
  public enum TransformationOneOf: Codable, Equatable, Sendable {
    /// Treat the dataset as free-form text and apply the same free text
    /// transformation everywhere.
    indirect case infoTypeTransformations(InfoTypeTransformations)
    /// Treat the dataset as structured. Transformations can be applied to
    /// specific locations within structured datasets, such as transforming
    /// a column within a table.
    indirect case recordTransformations(RecordTransformations)
    /// Treat the dataset as an image and redact.
    indirect case imageTransformations(ImageTransformations)
  }

  /// The type URL for `DeidentifyConfig`: `"type.googleapis.com/google.privacy.dlp.v2.DeidentifyConfig"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.DeidentifyConfig"
  }

  /// Initialize an instance of `DeidentifyConfig` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.privacy.dlp.v2.DeidentifyConfig"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `DeidentifyConfig` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
