// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request to de-identify a ContentItem.
public struct DeidentifyContentRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Parent resource name.
  ///
  /// The format of this value varies depending on whether you have [specified a
  /// processing
  /// location](https://docs.cloud.google.com/sensitive-data-protection/docs/specifying-location):
  ///
  /// + Projects scope, location specified:
  ///   `projects/{project_id}/locations/{location_id}`
  /// + Projects scope, no location specified (defaults to global):
  ///   `projects/{project_id}`
  ///
  /// The following example `parent` string specifies a parent project with the
  /// identifier `example-project`, and specifies the `europe-west3` location
  /// for processing data:
  ///
  ///     parent=projects/example-project/locations/europe-west3
  public var parent: Swift.String = Swift.String()

  /// Configuration for the de-identification of the content item.
  /// Items specified here will override the template referenced by the
  /// deidentify_template_name argument.
  public var deidentifyConfig: DeidentifyConfig? = nil

  /// Configuration for the inspector.
  /// Items specified here will override the template referenced by the
  /// inspect_template_name argument.
  public var inspectConfig: InspectConfig? = nil

  /// The item to de-identify. Will be treated as text.
  ///
  /// This value must be of type
  /// [Table][google.privacy.dlp.v2.Table] if your
  /// [deidentify_config][google.privacy.dlp.v2.DeidentifyContentRequest.deidentify_config]
  /// is a
  /// [RecordTransformations][google.privacy.dlp.v2.RecordTransformations]
  /// object.
  ///
  /// [google.privacy.dlp.v2.DeidentifyContentRequest.deidentify_config]: <doc:DeidentifyContentRequest/deidentifyConfig>
  /// [google.privacy.dlp.v2.RecordTransformations]: <doc:RecordTransformations>
  /// [google.privacy.dlp.v2.Table]: <doc:Table>
  public var item: ContentItem? = nil

  /// Template to use. Any configuration directly specified in
  /// inspect_config will override those set in the template. Singular fields
  /// that are set in this request will replace their corresponding fields in the
  /// template. Repeated fields are appended. Singular sub-messages and groups
  /// are recursively merged.
  public var inspectTemplateName: Swift.String = Swift.String()

  /// Template to use. Any configuration directly specified in
  /// deidentify_config will override those set in the template. Singular fields
  /// that are set in this request will replace their corresponding fields in the
  /// template. Repeated fields are appended. Singular sub-messages and groups
  /// are recursively merged.
  public var deidentifyTemplateName: Swift.String = Swift.String()

  /// Deprecated. This field has no effect.
  public var locationId: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `DeidentifyContentRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DeidentifyContentRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let deidentifyConfig = CodingKeys(stringValue: "deidentifyConfig")
    static let inspectConfig = CodingKeys(stringValue: "inspectConfig")
    static let item = CodingKeys(stringValue: "item")
    static let inspectTemplateName = CodingKeys(stringValue: "inspectTemplateName")
    static let deidentifyTemplateName = CodingKeys(stringValue: "deidentifyTemplateName")
    static let locationId = CodingKeys(stringValue: "locationId")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "deidentifyConfig",
      "inspectConfig",
      "item",
      "inspectTemplateName",
      "deidentifyTemplateName",
      "locationId",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    self.deidentifyConfig = try container.decodeIfPresent(
      DeidentifyConfig.self, forKey: .deidentifyConfig)
    self.inspectConfig = try container.decodeIfPresent(InspectConfig.self, forKey: .inspectConfig)
    self.item = try container.decodeIfPresent(ContentItem.self, forKey: .item)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .inspectTemplateName) {
      self.inspectTemplateName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .deidentifyTemplateName)
    {
      self.deidentifyTemplateName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .locationId) {
      self.locationId = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encodeIfPresent(self.deidentifyConfig, forKey: .deidentifyConfig)
    try container.encodeIfPresent(self.inspectConfig, forKey: .inspectConfig)
    try container.encodeIfPresent(self.item, forKey: .item)
    try container.encode(self.inspectTemplateName, forKey: .inspectTemplateName)
    try container.encode(self.deidentifyTemplateName, forKey: .deidentifyTemplateName)
    try container.encode(self.locationId, forKey: .locationId)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.DeidentifyContentRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
