// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// How often existing tables should have their profiles refreshed.
/// New tables are scanned as quickly as possible depending on system
/// capacity.
public struct DiscoveryCloudSqlGenerationCadence: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// When to reprofile if the schema has changed.
  public var schemaModifiedCadence: DiscoveryCloudSqlGenerationCadence.SchemaModifiedCadence? = nil

  /// Data changes (non-schema changes) in Cloud SQL tables can't trigger
  /// reprofiling. If you set this field, profiles are refreshed at this
  /// frequency regardless of whether the underlying tables have changed.
  /// Defaults to never.
  public var refreshFrequency: DataProfileUpdateFrequency = DataProfileUpdateFrequency()

  /// Governs when to update data profiles when the inspection rules
  /// defined by the `InspectTemplate` change.
  /// If not set, changing the template will not cause a data profile to update.
  public var inspectTemplateModifiedCadence: DiscoveryInspectTemplateModifiedCadence? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `DiscoveryCloudSqlGenerationCadence`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DiscoveryCloudSqlGenerationCadence().with { $0.schemaModifiedCadence = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let schemaModifiedCadence = CodingKeys(stringValue: "schemaModifiedCadence")
    static let refreshFrequency = CodingKeys(stringValue: "refreshFrequency")
    static let inspectTemplateModifiedCadence = CodingKeys(
      stringValue: "inspectTemplateModifiedCadence")

    static let _knownKeys: Set<Swift.String> = [
      "schemaModifiedCadence",
      "refreshFrequency",
      "inspectTemplateModifiedCadence",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.schemaModifiedCadence = try container.decodeIfPresent(
      DiscoveryCloudSqlGenerationCadence.SchemaModifiedCadence.self, forKey: .schemaModifiedCadence)
    if let value = try container.decodeIfPresent(
      DataProfileUpdateFrequency.self, forKey: .refreshFrequency)
    {
      self.refreshFrequency = value
    }
    self.inspectTemplateModifiedCadence = try container.decodeIfPresent(
      DiscoveryInspectTemplateModifiedCadence.self, forKey: .inspectTemplateModifiedCadence)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.schemaModifiedCadence, forKey: .schemaModifiedCadence)
    try container.encode(self.refreshFrequency, forKey: .refreshFrequency)
    try container.encodeIfPresent(
      self.inspectTemplateModifiedCadence, forKey: .inspectTemplateModifiedCadence)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// How frequently to modify the profile when the table's schema is modified.
  public struct SchemaModifiedCadence: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The types of schema modifications to consider.
    /// Defaults to NEW_COLUMNS.
    public var types:
      [DiscoveryCloudSqlGenerationCadence.SchemaModifiedCadence.CloudSqlSchemaModification] = []

    /// Frequency to regenerate data profiles when the schema is modified.
    /// Defaults to monthly.
    public var frequency: DataProfileUpdateFrequency = DataProfileUpdateFrequency()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `SchemaModifiedCadence`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SchemaModifiedCadence().with { $0.types = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let types = CodingKeys(stringValue: "types")
      static let frequency = CodingKeys(stringValue: "frequency")

      static let _knownKeys: Set<Swift.String> = [
        "types",
        "frequency",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        [DiscoveryCloudSqlGenerationCadence.SchemaModifiedCadence.CloudSqlSchemaModification].self,
        forKey: .types)
      {
        self.types = value
      }
      if let value = try container.decodeIfPresent(
        DataProfileUpdateFrequency.self, forKey: .frequency)
      {
        self.frequency = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.types, forKey: .types)
      try container.encode(self.frequency, forKey: .frequency)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The type of modification that causes a profile update.
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum CloudSqlSchemaModification: Codable, Equatable, Hashable, Sendable {
      /// Unused.
      case sqlSchemaModificationUnspecified
      /// New columns have appeared.
      case newColumns
      /// Columns have been removed from the table.
      case removedColumns
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .sqlSchemaModificationUnspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .sqlSchemaModificationUnspecified: return 0
        case .newColumns: return 1
        case .removedColumns: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .sqlSchemaModificationUnspecified: return "SQL_SCHEMA_MODIFICATION_UNSPECIFIED"
        case .newColumns: return "NEW_COLUMNS"
        case .removedColumns: return "REMOVED_COLUMNS"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:CloudSqlSchemaModification/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "SQL_SCHEMA_MODIFICATION_UNSPECIFIED": self = .sqlSchemaModificationUnspecified
        case "NEW_COLUMNS": self = .newColumns
        case "REMOVED_COLUMNS": self = .removedColumns
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:CloudSqlSchemaModification/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .sqlSchemaModificationUnspecified
        case 1: self = .newColumns
        case 2: self = .removedColumns
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: any Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: any Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .sqlSchemaModificationUnspecified:
          return try container.encode("SQL_SCHEMA_MODIFICATION_UNSPECIFIED")
        case .newColumns: return try container.encode("NEW_COLUMNS")
        case .removedColumns: return try container.encode("REMOVED_COLUMNS")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// The type URL for `SchemaModifiedCadence`: `"type.googleapis.com/google.privacy.dlp.v2.DiscoveryCloudSqlGenerationCadence.SchemaModifiedCadence"`.
    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.privacy.dlp.v2.DiscoveryCloudSqlGenerationCadence.SchemaModifiedCadence"
    }

    /// Initialize an instance of `SchemaModifiedCadence` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.privacy.dlp.v2.DiscoveryCloudSqlGenerationCadence.SchemaModifiedCadence"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `SchemaModifiedCadence` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The type URL for `DiscoveryCloudSqlGenerationCadence`: `"type.googleapis.com/google.privacy.dlp.v2.DiscoveryCloudSqlGenerationCadence"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.DiscoveryCloudSqlGenerationCadence"
  }

  /// Initialize an instance of `DiscoveryCloudSqlGenerationCadence` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.privacy.dlp.v2.DiscoveryCloudSqlGenerationCadence"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `DiscoveryCloudSqlGenerationCadence` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
