// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Determines what tables will have profiles generated within an organization
/// or project. Includes the ability to filter by regular expression patterns
/// on project ID, location, instance, database, and database resource name.
public struct DiscoveryCloudSqlFilter: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Whether the filter applies to a specific set of database resources or all
  /// other database resources within the location being profiled. The first
  /// filter to match will be applied, regardless of the condition. If none is
  /// set, will default to `others`.
  public var filter: FilterOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `DiscoveryCloudSqlFilter`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DiscoveryCloudSqlFilter().with { $0.collection = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let collection = CodingKeys(stringValue: "collection")
    static let others = CodingKeys(stringValue: "others")
    static let databaseResourceReference = CodingKeys(stringValue: "databaseResourceReference")

    static let _knownKeys: Set<Swift.String> = [
      "collection",
      "others",
      "databaseResourceReference",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var filter: FilterOneOf? = nil
    let filterCheckAndSet = {
      if filter != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'filter'"))
      }
      filter = $0
    }
    if let collection = try container.decodeIfPresent(
      DatabaseResourceCollection.self, forKey: .collection)
    {
      try filterCheckAndSet(.collection(collection))
    }
    if let others = try container.decodeIfPresent(AllOtherDatabaseResources.self, forKey: .others) {
      try filterCheckAndSet(.others(others))
    }
    if let databaseResourceReference = try container.decodeIfPresent(
      DatabaseResourceReference.self, forKey: .databaseResourceReference)
    {
      try filterCheckAndSet(.databaseResourceReference(databaseResourceReference))
    }
    self.filter = filter
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.filter {
      switch choice {
      case .collection(let value):
        try container.encode(value, forKey: .collection)
      case .others(let value):
        try container.encode(value, forKey: .others)
      case .databaseResourceReference(let value):
        try container.encode(value, forKey: .databaseResourceReference)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Whether the filter applies to a specific set of database resources or all
  /// other database resources within the location being profiled. The first
  /// filter to match will be applied, regardless of the condition. If none is
  /// set, will default to `others`.
  public enum FilterOneOf: Codable, Equatable, Sendable {
    /// A specific set of database resources for this filter to apply to.
    indirect case collection(DatabaseResourceCollection)
    /// Catch-all. This should always be the last target in the list because
    /// anything above it will apply first. Should only appear once in a
    /// configuration. If none is specified, a default one will be added
    /// automatically.
    indirect case others(AllOtherDatabaseResources)
    /// The database resource to scan. Targets including this can only include
    /// one target (the target with this database resource reference).
    indirect case databaseResourceReference(DatabaseResourceReference)
  }

  /// The type URL for `DiscoveryCloudSqlFilter`: `"type.googleapis.com/google.privacy.dlp.v2.DiscoveryCloudSqlFilter"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.DiscoveryCloudSqlFilter"
  }

  /// Initialize an instance of `DiscoveryCloudSqlFilter` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.privacy.dlp.v2.DiscoveryCloudSqlFilter"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `DiscoveryCloudSqlFilter` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
