// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Requirements that must be true before a table is scanned in discovery for the
/// first time. There is an AND relationship between the top-level attributes.
/// Additionally, minimum conditions with an OR relationship that must be met
/// before Cloud DLP scans a table can be set (like a minimum row count or a
/// minimum table age).
public struct DiscoveryBigQueryConditions: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// BigQuery table must have been created after this date. Used to avoid
  /// backfilling.
  public var createdAfter: GoogleWKT.WKTTimestamp? = nil

  /// At least one of the conditions must be true for a table to be scanned.
  public var orConditions: DiscoveryBigQueryConditions.OrConditions? = nil

  /// The type of BigQuery tables to scan. If nothing is set the default
  /// behavior is to scan only tables of type TABLE and to give errors
  /// for all unsupported tables.
  public var includedTypes: IncludedTypesOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `DiscoveryBigQueryConditions`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DiscoveryBigQueryConditions().with { $0.createdAfter = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let createdAfter = CodingKeys(stringValue: "createdAfter")
    static let types = CodingKeys(stringValue: "types")
    static let typeCollection = CodingKeys(stringValue: "typeCollection")
    static let orConditions = CodingKeys(stringValue: "orConditions")

    static let _knownKeys: Set<Swift.String> = [
      "createdAfter",
      "types",
      "typeCollection",
      "orConditions",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.createdAfter = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createdAfter)
    self.orConditions = try container.decodeIfPresent(
      DiscoveryBigQueryConditions.OrConditions.self, forKey: .orConditions)

    var includedTypes: IncludedTypesOneOf? = nil
    let includedTypesCheckAndSet = {
      if includedTypes != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'includedTypes'"))
      }
      includedTypes = $0
    }
    if let types = try container.decodeIfPresent(BigQueryTableTypes.self, forKey: .types) {
      try includedTypesCheckAndSet(.types(types))
    }
    if let typeCollection = try container.decodeIfPresent(
      BigQueryTableTypeCollection.self, forKey: .typeCollection)
    {
      try includedTypesCheckAndSet(.typeCollection(typeCollection))
    }
    self.includedTypes = includedTypes
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.createdAfter, forKey: .createdAfter)
    try container.encodeIfPresent(self.orConditions, forKey: .orConditions)

    if let choice = self.includedTypes {
      switch choice {
      case .types(let value):
        try container.encode(value, forKey: .types)
      case .typeCollection(let value):
        try container.encode(value, forKey: .typeCollection)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// There is an OR relationship between these attributes. They are used to
  /// determine if a table should be scanned or not in Discovery.
  public struct OrConditions: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Minimum number of rows that should be present before Cloud DLP
    /// profiles a table
    public var minRowCount: Swift.Int32 = Swift.Int32()

    /// Minimum age a table must have before Cloud DLP can profile it. Value must
    /// be 1 hour or greater.
    public var minAge: GoogleWKT.WKTDuration? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `OrConditions`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = OrConditions().with { $0.minRowCount = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let minRowCount = CodingKeys(stringValue: "minRowCount")
      static let minAge = CodingKeys(stringValue: "minAge")

      static let _knownKeys: Set<Swift.String> = [
        "minRowCount",
        "minAge",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .minRowCount) {
        self.minRowCount = value
      }
      self.minAge = try container.decodeIfPresent(GoogleWKT.WKTDuration.self, forKey: .minAge)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.minRowCount, forKey: .minRowCount)
      try container.encodeIfPresent(self.minAge, forKey: .minAge)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The type URL for `OrConditions`: `"type.googleapis.com/google.privacy.dlp.v2.DiscoveryBigQueryConditions.OrConditions"`.
    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.privacy.dlp.v2.DiscoveryBigQueryConditions.OrConditions"
    }

    /// Initialize an instance of `OrConditions` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.privacy.dlp.v2.DiscoveryBigQueryConditions.OrConditions"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `OrConditions` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The type of BigQuery tables to scan. If nothing is set the default
  /// behavior is to scan only tables of type TABLE and to give errors
  /// for all unsupported tables.
  public enum IncludedTypesOneOf: Codable, Equatable, Sendable {
    /// Restrict discovery to specific table types.
    indirect case types(BigQueryTableTypes)
    /// Restrict discovery to categories of table types.
    case typeCollection(BigQueryTableTypeCollection)
  }

  /// The type URL for `DiscoveryBigQueryConditions`: `"type.googleapis.com/google.privacy.dlp.v2.DiscoveryBigQueryConditions"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.DiscoveryBigQueryConditions"
  }

  /// Initialize an instance of `DiscoveryBigQueryConditions` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.privacy.dlp.v2.DiscoveryBigQueryConditions"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `DiscoveryBigQueryConditions` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
