// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A domain represents a thematic category that a data profile can fall under.
public struct Domain: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// A domain category that this profile is related to.
  public var category: Domain.Category = Domain.Category()

  /// The collection of signals that influenced selection of the category.
  public var signals: [Domain.Signal] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Domain`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Domain().with { $0.category = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let category = CodingKeys(stringValue: "category")
    static let signals = CodingKeys(stringValue: "signals")

    static let _knownKeys: Set<Swift.String> = [
      "category",
      "signals",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Domain.Category.self, forKey: .category) {
      self.category = value
    }
    if let value = try container.decodeIfPresent([Domain.Signal].self, forKey: .signals) {
      self.signals = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.category, forKey: .category)
    try container.encode(self.signals, forKey: .signals)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// This enum defines the various domain categories a data profile can fall
  /// under.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Category: Codable, Equatable, Hashable, Sendable {
    /// Category unspecified.
    case unspecified
    /// Indicates that the data profile is related to artificial intelligence.
    /// When set, all findings stored to Security Command Center will set the
    /// corresponding AI domain field of `Finding` objects.
    case ai
    /// Indicates that the data profile is related to code.
    case code
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .ai: return 1
      case .code: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CATEGORY_UNSPECIFIED"
      case .ai: return "AI"
      case .code: return "CODE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Category/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CATEGORY_UNSPECIFIED": self = .unspecified
      case "AI": self = .ai
      case "CODE": self = .code
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Category/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .ai
      case 2: self = .code
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("CATEGORY_UNSPECIFIED")
      case .ai: return try container.encode("AI")
      case .code: return try container.encode("CODE")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The signal used to determine the category.
  /// New values may be added in the future.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Signal: Codable, Equatable, Hashable, Sendable {
    /// Unused.
    case unspecified
    /// One or more machine learning models are present.
    case model
    /// A table appears to contain text embeddings.
    case textEmbedding
    /// The [Cloud SQL Vertex
    /// AI](https://docs.cloud.google.com/sql/docs/postgres/integrate-cloud-sql-with-vertex-ai)
    /// plugin is installed on the database.
    case vertexPlugin
    /// Support for [Cloud SQL vector
    /// embeddings](https://docs.cloud.google.com/sql/docs/mysql/enable-vector-search)
    /// is enabled on the database.
    case vectorPlugin
    /// Source code is present.
    case sourceCode
    /// If the service determines the category type. For example, Vertex AI
    /// assets would always have a `Category` of `AI`.
    case service
    /// A table appears to contain embeddings of any type (for example, text,
    /// image, multimodal). The `TEXT_EMBEDDING` signal might also be present if
    /// the table contains text embeddings.
    case embedding
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .model: return 1
      case .textEmbedding: return 2
      case .vertexPlugin: return 3
      case .vectorPlugin: return 4
      case .sourceCode: return 5
      case .service: return 6
      case .embedding: return 7
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "SIGNAL_UNSPECIFIED"
      case .model: return "MODEL"
      case .textEmbedding: return "TEXT_EMBEDDING"
      case .vertexPlugin: return "VERTEX_PLUGIN"
      case .vectorPlugin: return "VECTOR_PLUGIN"
      case .sourceCode: return "SOURCE_CODE"
      case .service: return "SERVICE"
      case .embedding: return "EMBEDDING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Signal/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "SIGNAL_UNSPECIFIED": self = .unspecified
      case "MODEL": self = .model
      case "TEXT_EMBEDDING": self = .textEmbedding
      case "EMBEDDING": self = .embedding
      case "VERTEX_PLUGIN": self = .vertexPlugin
      case "VECTOR_PLUGIN": self = .vectorPlugin
      case "SOURCE_CODE": self = .sourceCode
      case "SERVICE": self = .service
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Signal/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .model
      case 2: self = .textEmbedding
      case 3: self = .vertexPlugin
      case 4: self = .vectorPlugin
      case 5: self = .sourceCode
      case 6: self = .service
      case 7: self = .embedding
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("SIGNAL_UNSPECIFIED")
      case .model: return try container.encode("MODEL")
      case .textEmbedding: return try container.encode("TEXT_EMBEDDING")
      case .vertexPlugin: return try container.encode("VERTEX_PLUGIN")
      case .vectorPlugin: return try container.encode("VECTOR_PLUGIN")
      case .sourceCode: return try container.encode("SOURCE_CODE")
      case .service: return try container.encode("SERVICE")
      case .embedding: return try container.encode("EMBEDDING")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.Domain"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
