// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The rule to exclude findings based on a hotword. For record inspection of
/// tables, column names are considered hotwords. An example of this is to
/// exclude a finding if it belongs to a BigQuery column that matches a specific
/// pattern.
public struct ExcludeByHotword: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Regular expression pattern defining what qualifies as a hotword.
  public var hotwordRegex: CustomInfoType.Regex? = nil

  /// Range of characters within which the entire hotword must reside.
  /// The total length of the window cannot exceed 1000 characters.
  /// The windowBefore property in proximity should be set to 1 if the hotword
  /// needs to be included in a column header.
  public var proximity: CustomInfoType.DetectionRule.Proximity? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ExcludeByHotword`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ExcludeByHotword().with { $0.hotwordRegex = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let hotwordRegex = CodingKeys(stringValue: "hotwordRegex")
    static let proximity = CodingKeys(stringValue: "proximity")

    static let _knownKeys: Set<Swift.String> = [
      "hotwordRegex",
      "proximity",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.hotwordRegex = try container.decodeIfPresent(
      CustomInfoType.Regex.self, forKey: .hotwordRegex)
    self.proximity = try container.decodeIfPresent(
      CustomInfoType.DetectionRule.Proximity.self, forKey: .proximity)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.hotwordRegex, forKey: .hotwordRegex)
    try container.encodeIfPresent(self.proximity, forKey: .proximity)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `ExcludeByHotword`: `"type.googleapis.com/google.privacy.dlp.v2.ExcludeByHotword"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.ExcludeByHotword"
  }

  /// Initialize an instance of `ExcludeByHotword` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.privacy.dlp.v2.ExcludeByHotword"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `ExcludeByHotword` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
