// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Match file stores (e.g. buckets) using filters.
public struct FileStoreCollection: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. To be included in the collection, a resource must meet all of the
  /// following requirements:
  ///
  ///  - If tag filters are provided, match all provided tag filters.
  ///  - If one or more patterns are specified, match at least one pattern.
  ///
  /// For a resource to match the tag filters, the resource must have all of the
  /// provided tags attached. Tags refer to Resource Manager tags bound to the
  /// resource or its ancestors. For more information, see [Manage
  /// schedules](https://docs.cloud.google.com/sensitive-data-protection/docs/profile-project-cloud-storage#manage-schedules).
  public var includeTags: TagFilters? = nil

  /// The first filter containing a pattern that matches a file store will be
  /// used.
  public var pattern: PatternOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `FileStoreCollection`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FileStoreCollection().with { $0.includeRegexes = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let includeRegexes = CodingKeys(stringValue: "includeRegexes")
    static let includeTags = CodingKeys(stringValue: "includeTags")

    static let _knownKeys: Set<Swift.String> = [
      "includeRegexes",
      "includeTags",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.includeTags = try container.decodeIfPresent(TagFilters.self, forKey: .includeTags)

    var pattern: PatternOneOf? = nil
    let patternCheckAndSet = {
      if pattern != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'pattern'"))
      }
      pattern = $0
    }
    if let includeRegexes = try container.decodeIfPresent(
      FileStoreRegexes.self, forKey: .includeRegexes)
    {
      try patternCheckAndSet(.includeRegexes(includeRegexes))
    }
    self.pattern = pattern
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.includeTags, forKey: .includeTags)

    if let choice = self.pattern {
      switch choice {
      case .includeRegexes(let value):
        try container.encode(value, forKey: .includeRegexes)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The first filter containing a pattern that matches a file store will be
  /// used.
  public enum PatternOneOf: Codable, Equatable, Sendable {
    /// Optional. A collection of regular expressions to match a file store
    /// against.
    indirect case includeRegexes(FileStoreRegexes)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.FileStoreCollection"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
