// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The profile for a file store.
///
/// * Cloud Storage: maps 1:1 with a bucket.
/// * Amazon S3: maps 1:1 with a bucket.
public struct FileStoreDataProfile: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The name of the profile.
  public var name: Swift.String = Swift.String()

  /// The resource type that was profiled.
  public var dataSourceType: DataSourceType? = nil

  /// The resource name of the project data profile for this file store.
  public var projectDataProfile: Swift.String = Swift.String()

  /// The Google Cloud project ID that owns the resource.
  /// For Amazon S3 buckets, this is the AWS Account Id.
  public var projectId: Swift.String = Swift.String()

  /// The location of the file store.
  ///
  /// * Cloud Storage:
  /// https://docs.cloud.google.com/storage/docs/locations#available-locations
  /// * Amazon S3:
  /// https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints
  public var fileStoreLocation: Swift.String = Swift.String()

  /// For resources that have multiple storage locations, these are those
  /// regions. For Cloud Storage this is the list of regions chosen for
  /// dual-region storage. `file_store_location` will normally be the
  /// corresponding multi-region for the list of individual locations. The first
  /// region is always picked as the processing and storage location for the data
  /// profile.
  public var dataStorageLocations: [Swift.String] = []

  /// The location type of the file store (region, dual-region, multi-region,
  /// etc). If dual-region, expect data_storage_locations to be populated.
  public var locationType: Swift.String = Swift.String()

  /// The file store path.
  ///
  /// * Cloud Storage: `gs://{bucket}`
  /// * Amazon S3: `s3://{bucket}`
  /// * Vertex AI dataset:
  /// `projects/{project_number}/locations/{location}/datasets/{dataset_id}`
  public var fileStorePath: Swift.String = Swift.String()

  /// The resource name of the resource profiled.
  /// https://cloud.google.com/apis/design/resource_names#full_resource_name
  ///
  /// Example format of an S3 bucket full resource name:
  /// `//cloudasset.googleapis.com/organizations/{org_id}/otherCloudConnections/aws/arn:aws:s3:::{bucket_name}`
  public var fullResource: Swift.String = Swift.String()

  /// The snapshot of the configurations used to generate the profile.
  public var configSnapshot: DataProfileConfigSnapshot? = nil

  /// Success or error status from the most recent profile generation attempt.
  /// May be empty if the profile is still being generated.
  public var profileStatus: ProfileStatus? = nil

  /// State of a profile.
  public var state: FileStoreDataProfile.State = FileStoreDataProfile.State()

  /// The last time the profile was generated.
  public var profileLastGenerated: GoogleWKT.WKTTimestamp? = nil

  /// How broadly a resource has been shared.
  public var resourceVisibility: ResourceVisibility = ResourceVisibility()

  /// The sensitivity score of this resource.
  public var sensitivityScore: SensitivityScore? = nil

  /// The data risk level of this resource.
  public var dataRiskLevel: DataRiskLevel? = nil

  /// The time the file store was first created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// The time the file store was last modified.
  public var lastModifiedTime: GoogleWKT.WKTTimestamp? = nil

  /// FileClusterSummary per each cluster.
  public var fileClusterSummaries: [FileClusterSummary] = []

  /// Attributes of the resource being profiled.
  /// Currently used attributes:
  ///
  /// * customer_managed_encryption: boolean
  ///     - true: the resource is encrypted with a customer-managed key.
  ///     - false: the resource is encrypted with a provider-managed key.
  public var resourceAttributes: [Swift.String: Value] = [:]

  /// The labels applied to the resource at the time the profile was generated.
  public var resourceLabels: [Swift.String: Swift.String] = [:]

  /// InfoTypes detected in this file store.
  public var fileStoreInfoTypeSummaries: [FileStoreInfoTypeSummary] = []

  /// The BigQuery table to which the sample findings are written.
  public var sampleFindingsTable: BigQueryTable? = nil

  /// The file store does not have any files. If the profiling operation failed,
  /// this is false.
  public var fileStoreIsEmpty: Swift.Bool = Swift.Bool()

  /// The tags attached to the resource, including any tags attached during
  /// profiling.
  public var tags: [Tag] = []

  /// Resources related to this profile.
  public var relatedResources: [RelatedResource] = []

  /// Domains associated with the profile.
  public var domains: [Domain] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `FileStoreDataProfile`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FileStoreDataProfile().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let dataSourceType = CodingKeys(stringValue: "dataSourceType")
    static let projectDataProfile = CodingKeys(stringValue: "projectDataProfile")
    static let projectId = CodingKeys(stringValue: "projectId")
    static let fileStoreLocation = CodingKeys(stringValue: "fileStoreLocation")
    static let dataStorageLocations = CodingKeys(stringValue: "dataStorageLocations")
    static let locationType = CodingKeys(stringValue: "locationType")
    static let fileStorePath = CodingKeys(stringValue: "fileStorePath")
    static let fullResource = CodingKeys(stringValue: "fullResource")
    static let configSnapshot = CodingKeys(stringValue: "configSnapshot")
    static let profileStatus = CodingKeys(stringValue: "profileStatus")
    static let state = CodingKeys(stringValue: "state")
    static let profileLastGenerated = CodingKeys(stringValue: "profileLastGenerated")
    static let resourceVisibility = CodingKeys(stringValue: "resourceVisibility")
    static let sensitivityScore = CodingKeys(stringValue: "sensitivityScore")
    static let dataRiskLevel = CodingKeys(stringValue: "dataRiskLevel")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let lastModifiedTime = CodingKeys(stringValue: "lastModifiedTime")
    static let fileClusterSummaries = CodingKeys(stringValue: "fileClusterSummaries")
    static let resourceAttributes = CodingKeys(stringValue: "resourceAttributes")
    static let resourceLabels = CodingKeys(stringValue: "resourceLabels")
    static let fileStoreInfoTypeSummaries = CodingKeys(stringValue: "fileStoreInfoTypeSummaries")
    static let sampleFindingsTable = CodingKeys(stringValue: "sampleFindingsTable")
    static let fileStoreIsEmpty = CodingKeys(stringValue: "fileStoreIsEmpty")
    static let tags = CodingKeys(stringValue: "tags")
    static let relatedResources = CodingKeys(stringValue: "relatedResources")
    static let domains = CodingKeys(stringValue: "domains")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "dataSourceType",
      "projectDataProfile",
      "projectId",
      "fileStoreLocation",
      "dataStorageLocations",
      "locationType",
      "fileStorePath",
      "fullResource",
      "configSnapshot",
      "profileStatus",
      "state",
      "profileLastGenerated",
      "resourceVisibility",
      "sensitivityScore",
      "dataRiskLevel",
      "createTime",
      "lastModifiedTime",
      "fileClusterSummaries",
      "resourceAttributes",
      "resourceLabels",
      "fileStoreInfoTypeSummaries",
      "sampleFindingsTable",
      "fileStoreIsEmpty",
      "tags",
      "relatedResources",
      "domains",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.dataSourceType = try container.decodeIfPresent(
      DataSourceType.self, forKey: .dataSourceType)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .projectDataProfile) {
      self.projectDataProfile = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .projectId) {
      self.projectId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .fileStoreLocation) {
      self.fileStoreLocation = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .dataStorageLocations)
    {
      self.dataStorageLocations = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .locationType) {
      self.locationType = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .fileStorePath) {
      self.fileStorePath = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .fullResource) {
      self.fullResource = value
    }
    self.configSnapshot = try container.decodeIfPresent(
      DataProfileConfigSnapshot.self, forKey: .configSnapshot)
    self.profileStatus = try container.decodeIfPresent(ProfileStatus.self, forKey: .profileStatus)
    if let value = try container.decodeIfPresent(FileStoreDataProfile.State.self, forKey: .state) {
      self.state = value
    }
    self.profileLastGenerated = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .profileLastGenerated)
    if let value = try container.decodeIfPresent(
      ResourceVisibility.self, forKey: .resourceVisibility)
    {
      self.resourceVisibility = value
    }
    self.sensitivityScore = try container.decodeIfPresent(
      SensitivityScore.self, forKey: .sensitivityScore)
    self.dataRiskLevel = try container.decodeIfPresent(DataRiskLevel.self, forKey: .dataRiskLevel)
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.lastModifiedTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .lastModifiedTime)
    if let value = try container.decodeIfPresent(
      [FileClusterSummary].self, forKey: .fileClusterSummaries)
    {
      self.fileClusterSummaries = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Value].self, forKey: .resourceAttributes)
    {
      self.resourceAttributes = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .resourceLabels)
    {
      self.resourceLabels = value
    }
    if let value = try container.decodeIfPresent(
      [FileStoreInfoTypeSummary].self, forKey: .fileStoreInfoTypeSummaries)
    {
      self.fileStoreInfoTypeSummaries = value
    }
    self.sampleFindingsTable = try container.decodeIfPresent(
      BigQueryTable.self, forKey: .sampleFindingsTable)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .fileStoreIsEmpty) {
      self.fileStoreIsEmpty = value
    }
    if let value = try container.decodeIfPresent([Tag].self, forKey: .tags) {
      self.tags = value
    }
    if let value = try container.decodeIfPresent([RelatedResource].self, forKey: .relatedResources)
    {
      self.relatedResources = value
    }
    if let value = try container.decodeIfPresent([Domain].self, forKey: .domains) {
      self.domains = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.dataSourceType, forKey: .dataSourceType)
    try container.encode(self.projectDataProfile, forKey: .projectDataProfile)
    try container.encode(self.projectId, forKey: .projectId)
    try container.encode(self.fileStoreLocation, forKey: .fileStoreLocation)
    try container.encode(self.dataStorageLocations, forKey: .dataStorageLocations)
    try container.encode(self.locationType, forKey: .locationType)
    try container.encode(self.fileStorePath, forKey: .fileStorePath)
    try container.encode(self.fullResource, forKey: .fullResource)
    try container.encodeIfPresent(self.configSnapshot, forKey: .configSnapshot)
    try container.encodeIfPresent(self.profileStatus, forKey: .profileStatus)
    try container.encode(self.state, forKey: .state)
    try container.encodeIfPresent(self.profileLastGenerated, forKey: .profileLastGenerated)
    try container.encode(self.resourceVisibility, forKey: .resourceVisibility)
    try container.encodeIfPresent(self.sensitivityScore, forKey: .sensitivityScore)
    try container.encodeIfPresent(self.dataRiskLevel, forKey: .dataRiskLevel)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.lastModifiedTime, forKey: .lastModifiedTime)
    try container.encode(self.fileClusterSummaries, forKey: .fileClusterSummaries)
    try container.encode(self.resourceAttributes, forKey: .resourceAttributes)
    try container.encode(self.resourceLabels, forKey: .resourceLabels)
    try container.encode(self.fileStoreInfoTypeSummaries, forKey: .fileStoreInfoTypeSummaries)
    try container.encodeIfPresent(self.sampleFindingsTable, forKey: .sampleFindingsTable)
    try container.encode(self.fileStoreIsEmpty, forKey: .fileStoreIsEmpty)
    try container.encode(self.tags, forKey: .tags)
    try container.encode(self.relatedResources, forKey: .relatedResources)
    try container.encode(self.domains, forKey: .domains)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Possible states of a profile. New items may be added.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Hashable, Sendable {
    /// Unused.
    case unspecified
    /// The profile is currently running. Once a profile has finished it will
    /// transition to DONE.
    case running
    /// The profile is no longer generating.
    /// If profile_status.status.code is 0, the profile succeeded, otherwise, it
    /// failed.
    case done
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .running: return 1
      case .done: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .running: return "RUNNING"
      case .done: return "DONE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "RUNNING": self = .running
      case "DONE": self = .done
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .running
      case 2: self = .done
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .running: return try container.encode("RUNNING")
      case .done: return try container.encode("DONE")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The type URL for `FileStoreDataProfile`: `"type.googleapis.com/google.privacy.dlp.v2.FileStoreDataProfile"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.FileStoreDataProfile"
  }

  /// Initialize an instance of `FileStoreDataProfile` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.privacy.dlp.v2.FileStoreDataProfile"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `FileStoreDataProfile` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
