// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Message used to identify file cluster type being profiled.
public struct FileClusterType: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// File cluster type.
  public var fileClusterType: FileClusterTypeOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `FileClusterType`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FileClusterType().with { $0.cluster = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let cluster = CodingKeys(stringValue: "cluster")

    static let _knownKeys: Set<Swift.String> = [
      "cluster"
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var fileClusterType: FileClusterTypeOneOf? = nil
    let fileClusterTypeCheckAndSet = {
      if fileClusterType != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'fileClusterType'"))
      }
      fileClusterType = $0
    }
    if let cluster = try container.decodeIfPresent(FileClusterType.Cluster.self, forKey: .cluster) {
      try fileClusterTypeCheckAndSet(.cluster(cluster))
    }
    self.fileClusterType = fileClusterType
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.fileClusterType {
      switch choice {
      case .cluster(let value):
        try container.encode(value, forKey: .cluster)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Cluster type. Each cluster corresponds to a set of file types.
  /// Over time, new types may be added and files may move between clusters.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Cluster: Codable, Equatable, Hashable, Sendable {
    /// Unused.
    case unspecified
    /// Unsupported files.
    case unknown
    /// Plain text.
    case text
    /// Structured data like CSV, TSV etc.
    case structuredData
    /// Source code.
    case sourceCode
    /// Rich document like docx, xlsx etc.
    case richDocument
    /// Images like jpeg, bmp.
    case image
    /// Archives and containers like .zip, .tar etc.
    case archive
    /// Multimedia like .mp4, .avi etc.
    case multimedia
    /// Executable files like .exe, .class, .apk etc.
    case executable
    /// AI models like .tflite etc.
    case aiModel
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .unknown: return 1
      case .text: return 2
      case .structuredData: return 3
      case .sourceCode: return 4
      case .richDocument: return 5
      case .image: return 6
      case .archive: return 7
      case .multimedia: return 8
      case .executable: return 9
      case .aiModel: return 10
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CLUSTER_UNSPECIFIED"
      case .unknown: return "CLUSTER_UNKNOWN"
      case .text: return "CLUSTER_TEXT"
      case .structuredData: return "CLUSTER_STRUCTURED_DATA"
      case .sourceCode: return "CLUSTER_SOURCE_CODE"
      case .richDocument: return "CLUSTER_RICH_DOCUMENT"
      case .image: return "CLUSTER_IMAGE"
      case .archive: return "CLUSTER_ARCHIVE"
      case .multimedia: return "CLUSTER_MULTIMEDIA"
      case .executable: return "CLUSTER_EXECUTABLE"
      case .aiModel: return "CLUSTER_AI_MODEL"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Cluster/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CLUSTER_UNSPECIFIED": self = .unspecified
      case "CLUSTER_UNKNOWN": self = .unknown
      case "CLUSTER_TEXT": self = .text
      case "CLUSTER_STRUCTURED_DATA": self = .structuredData
      case "CLUSTER_SOURCE_CODE": self = .sourceCode
      case "CLUSTER_RICH_DOCUMENT": self = .richDocument
      case "CLUSTER_IMAGE": self = .image
      case "CLUSTER_ARCHIVE": self = .archive
      case "CLUSTER_MULTIMEDIA": self = .multimedia
      case "CLUSTER_EXECUTABLE": self = .executable
      case "CLUSTER_AI_MODEL": self = .aiModel
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Cluster/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .unknown
      case 2: self = .text
      case 3: self = .structuredData
      case 4: self = .sourceCode
      case 5: self = .richDocument
      case 6: self = .image
      case 7: self = .archive
      case 8: self = .multimedia
      case 9: self = .executable
      case 10: self = .aiModel
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("CLUSTER_UNSPECIFIED")
      case .unknown: return try container.encode("CLUSTER_UNKNOWN")
      case .text: return try container.encode("CLUSTER_TEXT")
      case .structuredData: return try container.encode("CLUSTER_STRUCTURED_DATA")
      case .sourceCode: return try container.encode("CLUSTER_SOURCE_CODE")
      case .richDocument: return try container.encode("CLUSTER_RICH_DOCUMENT")
      case .image: return try container.encode("CLUSTER_IMAGE")
      case .archive: return try container.encode("CLUSTER_ARCHIVE")
      case .multimedia: return try container.encode("CLUSTER_MULTIMEDIA")
      case .executable: return try container.encode("CLUSTER_EXECUTABLE")
      case .aiModel: return try container.encode("CLUSTER_AI_MODEL")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// File cluster type.
  public enum FileClusterTypeOneOf: Codable, Equatable, Sendable {
    /// Cluster type.
    case cluster(FileClusterType.Cluster)
  }

  /// The type URL for `FileClusterType`: `"type.googleapis.com/google.privacy.dlp.v2.FileClusterType"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.FileClusterType"
  }

  /// Initialize an instance of `FileClusterType` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.privacy.dlp.v2.FileClusterType"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `FileClusterType` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
