// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// Definitions of file type groups to scan. New types will be added to this
/// list.
///
/// - Note: Adding cases to this enumeration is not considered a breaking change.
///   Always include an `@unknown default:` case when switching over this type.
///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
///   expecting specific values to remain unparsed; future releases may promote
///   them to named cases.
public enum FileType: Codable, Equatable, Hashable, Sendable {
  /// Includes all files.
  case unspecified
  /// Includes all file extensions not covered by another entry. Binary
  /// scanning attempts to convert the content of the file to utf_8 to scan
  /// the file.
  /// If you wish to avoid this fall back, specify one or more of the other
  /// file types in your storage scan.
  case binaryFile
  /// Included file extensions:
  ///   asc,asp, aspx, brf, c, cc,cfm, cgi, cpp, csv, cxx, c++, cs, css, dart,
  ///   dat, dot, eml,, epbub, ged, go, h, hh, hpp, hxx, h++, hs, html, htm,
  ///   mkd, markdown, m, ml, mli, perl, pl, plist, pm, php, phtml, pht,
  ///   properties, py, pyw, rb, rbw, rs, rss,  rc, scala, sh, sql, swift, tex,
  ///   shtml, shtm, xhtml, lhs, ics, ini, java, js, json, jsonl, kix, kml,
  ///   ocaml, md, txt, text, tsv, vb, vcard, vcs, wml, xcodeproj, xml, xsl, xsd,
  ///   yml, yaml.
  case textFile
  /// Included file extensions:
  ///   bmp, gif, jpg, jpeg, jpe, png. Setting
  /// [bytes_limit_per_file][google.privacy.dlp.v2.CloudStorageOptions.bytes_limit_per_file]
  /// or
  /// [bytes_limit_per_file_percent][google.privacy.dlp.v2.CloudStorageOptions.bytes_limit_per_file]
  /// has no effect on image files. Image inspection is restricted to the
  /// `global`, `us`, `asia`, and `europe` regions.
  ///
  /// [google.privacy.dlp.v2.CloudStorageOptions.bytes_limit_per_file]: <doc:CloudStorageOptions/bytesLimitPerFile>
  case image
  /// Microsoft Word files larger than 30 MB will be scanned as binary files.
  /// Included file extensions:
  ///   docx, dotx, docm, dotm. Setting `bytes_limit_per_file` or
  ///   `bytes_limit_per_file_percent` has no effect on Word files.
  case word
  /// PDF files larger than 30 MB will be scanned as binary files.
  /// Included file extensions:
  ///   pdf. Setting `bytes_limit_per_file` or `bytes_limit_per_file_percent`
  /// has no effect on PDF files.
  case pdf
  /// Included file extensions:
  ///   avro
  case avro
  /// Included file extensions:
  ///   csv
  case csv
  /// Included file extensions:
  ///   tsv
  case tsv
  /// Microsoft PowerPoint files larger than 30 MB will be scanned as binary
  /// files. Included file extensions:
  ///   pptx, pptm, potx, potm, pot. Setting `bytes_limit_per_file` or
  ///   `bytes_limit_per_file_percent` has no effect on PowerPoint files.
  case powerpoint
  /// Microsoft Excel files larger than 30 MB will be scanned as binary files.
  /// Included file extensions:
  ///   xlsx, xlsm, xltx, xltm. Setting `bytes_limit_per_file` or
  ///   `bytes_limit_per_file_percent` has no effect on Excel files.
  case excel
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown value is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  ///
  /// - Warning: Do not pattern-match specific integer values in this case;
  ///   future releases may promote them to named enum cases.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown value is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  ///
  /// - Warning: Do not pattern-match specific string literals in this case;
  ///   future releases may promote them to named enum cases.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .binaryFile: return 1
    case .textFile: return 2
    case .image: return 3
    case .word: return 5
    case .pdf: return 6
    case .avro: return 7
    case .csv: return 8
    case .tsv: return 9
    case .powerpoint: return 11
    case .excel: return 12
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "FILE_TYPE_UNSPECIFIED"
    case .binaryFile: return "BINARY_FILE"
    case .textFile: return "TEXT_FILE"
    case .image: return "IMAGE"
    case .word: return "WORD"
    case .pdf: return "PDF"
    case .avro: return "AVRO"
    case .csv: return "CSV"
    case .tsv: return "TSV"
    case .powerpoint: return "POWERPOINT"
    case .excel: return "EXCEL"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:FileType/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "FILE_TYPE_UNSPECIFIED": self = .unspecified
    case "BINARY_FILE": self = .binaryFile
    case "TEXT_FILE": self = .textFile
    case "IMAGE": self = .image
    case "WORD": self = .word
    case "PDF": self = .pdf
    case "AVRO": self = .avro
    case "CSV": self = .csv
    case "TSV": self = .tsv
    case "POWERPOINT": self = .powerpoint
    case "EXCEL": self = .excel
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:FileType/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .binaryFile
    case 2: self = .textFile
    case 3: self = .image
    case 5: self = .word
    case 6: self = .pdf
    case 7: self = .avro
    case 8: self = .csv
    case 9: self = .tsv
    case 11: self = .powerpoint
    case 12: self = .excel
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode("FILE_TYPE_UNSPECIFIED")
    case .binaryFile: return try container.encode("BINARY_FILE")
    case .textFile: return try container.encode("TEXT_FILE")
    case .image: return try container.encode("IMAGE")
    case .word: return try container.encode("WORD")
    case .pdf: return try container.encode("PDF")
    case .avro: return try container.encode("AVRO")
    case .csv: return try container.encode("CSV")
    case .tsv: return try container.encode("TSV")
    case .powerpoint: return try container.encode("POWERPOINT")
    case .excel: return try container.encode("EXCEL")
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
