// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The results of an inspect DataSource job.
public struct InspectDataSourceDetails: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The configuration used for this job.
  public var requestedOptions: InspectDataSourceDetails.RequestedOptions? = nil

  /// Output only. A summary of the outcome of this inspection job.
  public var result: InspectDataSourceDetails.Result? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `InspectDataSourceDetails`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = InspectDataSourceDetails().with { $0.requestedOptions = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let requestedOptions = CodingKeys(stringValue: "requestedOptions")
    static let result = CodingKeys(stringValue: "result")

    static let _knownKeys: Set<Swift.String> = [
      "requestedOptions",
      "result",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.requestedOptions = try container.decodeIfPresent(
      InspectDataSourceDetails.RequestedOptions.self, forKey: .requestedOptions)
    self.result = try container.decodeIfPresent(
      InspectDataSourceDetails.Result.self, forKey: .result)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.requestedOptions, forKey: .requestedOptions)
    try container.encodeIfPresent(self.result, forKey: .result)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Snapshot of the inspection configuration.
  public struct RequestedOptions: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Output only. If run with an InspectTemplate, a snapshot of its state at
    /// the time of this run.
    public var snapshotInspectTemplate: InspectTemplate? = nil

    /// Inspect config.
    public var jobConfig: InspectJobConfig? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `RequestedOptions`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RequestedOptions().with { $0.snapshotInspectTemplate = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let snapshotInspectTemplate = CodingKeys(stringValue: "snapshotInspectTemplate")
      static let jobConfig = CodingKeys(stringValue: "jobConfig")

      static let _knownKeys: Set<Swift.String> = [
        "snapshotInspectTemplate",
        "jobConfig",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.snapshotInspectTemplate = try container.decodeIfPresent(
        InspectTemplate.self, forKey: .snapshotInspectTemplate)
      self.jobConfig = try container.decodeIfPresent(InspectJobConfig.self, forKey: .jobConfig)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.snapshotInspectTemplate, forKey: .snapshotInspectTemplate)
      try container.encodeIfPresent(self.jobConfig, forKey: .jobConfig)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The type URL for `RequestedOptions`: `"type.googleapis.com/google.privacy.dlp.v2.InspectDataSourceDetails.RequestedOptions"`.
    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.privacy.dlp.v2.InspectDataSourceDetails.RequestedOptions"
    }

    /// Initialize an instance of `RequestedOptions` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.privacy.dlp.v2.InspectDataSourceDetails.RequestedOptions"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `RequestedOptions` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// All Result fields are updated while the job is processing.
  public struct Result: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Total size in bytes that were processed.
    public var processedBytes: Swift.Int64 = Swift.Int64()

    /// Estimate of the number of bytes to process.
    public var totalEstimatedBytes: Swift.Int64 = Swift.Int64()

    /// Statistics of how many instances of each info type were found during
    /// inspect job.
    public var infoTypeStats: [InfoTypeStats] = []

    /// Number of rows scanned after sampling and time filtering (applicable for
    /// row based stores such as BigQuery).
    public var numRowsProcessed: Swift.Int64 = Swift.Int64()

    /// Statistics related to the processing of hybrid inspect.
    public var hybridStats: HybridInspectStatistics? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Result`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Result().with { $0.processedBytes = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let processedBytes = CodingKeys(stringValue: "processedBytes")
      static let totalEstimatedBytes = CodingKeys(stringValue: "totalEstimatedBytes")
      static let infoTypeStats = CodingKeys(stringValue: "infoTypeStats")
      static let numRowsProcessed = CodingKeys(stringValue: "numRowsProcessed")
      static let hybridStats = CodingKeys(stringValue: "hybridStats")

      static let _knownKeys: Set<Swift.String> = [
        "processedBytes",
        "totalEstimatedBytes",
        "infoTypeStats",
        "numRowsProcessed",
        "hybridStats",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .processedBytes) {
        self.processedBytes = value
      }
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .totalEstimatedBytes) {
        self.totalEstimatedBytes = value
      }
      if let value = try container.decodeIfPresent([InfoTypeStats].self, forKey: .infoTypeStats) {
        self.infoTypeStats = value
      }
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .numRowsProcessed) {
        self.numRowsProcessed = value
      }
      self.hybridStats = try container.decodeIfPresent(
        HybridInspectStatistics.self, forKey: .hybridStats)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.processedBytes, forKey: .processedBytes)
      try container.encode(self.totalEstimatedBytes, forKey: .totalEstimatedBytes)
      try container.encode(self.infoTypeStats, forKey: .infoTypeStats)
      try container.encode(self.numRowsProcessed, forKey: .numRowsProcessed)
      try container.encodeIfPresent(self.hybridStats, forKey: .hybridStats)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The type URL for `Result`: `"type.googleapis.com/google.privacy.dlp.v2.InspectDataSourceDetails.Result"`.
    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.privacy.dlp.v2.InspectDataSourceDetails.Result"
    }

    /// Initialize an instance of `Result` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.privacy.dlp.v2.InspectDataSourceDetails.Result"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `Result` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The type URL for `InspectDataSourceDetails`: `"type.googleapis.com/google.privacy.dlp.v2.InspectDataSourceDetails"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.InspectDataSourceDetails"
  }

  /// Initialize an instance of `InspectDataSourceDetails` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.privacy.dlp.v2.InspectDataSourceDetails"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `InspectDataSourceDetails` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
