// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Configuration description of the scanning process.
/// When used with redactContent only info_types and min_likelihood are currently
/// used.
public struct InspectConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Restricts what info_types to look for. The values must correspond to
  /// InfoType values returned by ListInfoTypes or listed at
  /// https://docs.cloud.google.com/sensitive-data-protection/docs/infotypes-reference.
  ///
  /// When no InfoTypes or CustomInfoTypes are specified in a request, the
  /// system may automatically choose a default list of detectors to run, which
  /// may change over time.
  ///
  /// If you need precise control and predictability as to what detectors are
  /// run you should specify specific InfoTypes listed in the reference,
  /// otherwise a default list will be used, which may change over time.
  public var infoTypes: [InfoType] = []

  /// Only returns findings equal to or above this threshold. The default is
  /// POSSIBLE.
  ///
  /// In general, the highest likelihood setting yields the fewest findings in
  /// results and the lowest chance of a false positive. For more information,
  /// see [Match
  /// likelihood](https://docs.cloud.google.com/sensitive-data-protection/docs/likelihood).
  public var minLikelihood: Likelihood = Likelihood()

  /// Minimum likelihood per infotype. For each infotype, a user can specify a
  /// minimum likelihood. The system only returns a finding if its likelihood is
  /// above this threshold. If this field is not set, the system uses the
  /// InspectConfig min_likelihood.
  public var minLikelihoodPerInfoType: [InspectConfig.InfoTypeLikelihood] = []

  /// Configuration to control the number of findings returned.
  /// This is not used for data profiling.
  ///
  /// When redacting sensitive data from images, finding limits don't apply. They
  /// can cause unexpected or inconsistent results, where only some data is
  /// redacted. Don't include finding limits in
  /// [RedactImage][google.privacy.dlp.v2.DlpService.RedactImage]
  /// requests. Otherwise, Cloud DLP returns an error.
  ///
  /// When set within an
  /// [InspectJobConfig][google.privacy.dlp.v2.InspectJobConfig], the specified
  /// maximum values aren't hard limits. If an inspection job reaches these
  /// limits, the job ends gradually, not abruptly. Therefore, the actual number
  /// of findings that Cloud DLP returns can be multiple times higher than these
  /// maximum values.
  ///
  /// [google.privacy.dlp.v2.DlpService.RedactImage]: <doc:DlpServiceClient/redactImage(request:options:)>
  /// [google.privacy.dlp.v2.InspectJobConfig]: <doc:InspectJobConfig>
  public var limits: InspectConfig.FindingLimits? = nil

  /// When true, a contextual quote from the data that triggered a finding is
  /// included in the response; see
  /// [Finding.quote][google.privacy.dlp.v2.Finding.quote]. This is not used for
  /// data profiling.
  ///
  /// [google.privacy.dlp.v2.Finding.quote]: <doc:Finding/quote>
  public var includeQuote: Swift.Bool = Swift.Bool()

  /// When true, excludes type information of the findings.
  /// This is not used for data profiling.
  public var excludeInfoTypes: Swift.Bool = Swift.Bool()

  /// CustomInfoTypes provided by the user. See
  /// https://docs.cloud.google.com/sensitive-data-protection/docs/creating-custom-infotypes
  /// to learn more.
  public var customInfoTypes: [CustomInfoType] = []

  /// Deprecated and unused.
  public var contentOptions: [ContentOption] = []

  /// Set of rules to apply to the findings for this InspectConfig.
  /// Exclusion rules, contained in the set are executed in the end, other
  /// rules are executed in the order they are specified for each info type. Not
  /// supported for the `metadata_key_value_expression` CustomInfoType.
  public var ruleSet: [InspectionRuleSet] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `InspectConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = InspectConfig().with { $0.infoTypes = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let infoTypes = CodingKeys(stringValue: "infoTypes")
    static let minLikelihood = CodingKeys(stringValue: "minLikelihood")
    static let minLikelihoodPerInfoType = CodingKeys(stringValue: "minLikelihoodPerInfoType")
    static let limits = CodingKeys(stringValue: "limits")
    static let includeQuote = CodingKeys(stringValue: "includeQuote")
    static let excludeInfoTypes = CodingKeys(stringValue: "excludeInfoTypes")
    static let customInfoTypes = CodingKeys(stringValue: "customInfoTypes")
    static let contentOptions = CodingKeys(stringValue: "contentOptions")
    static let ruleSet = CodingKeys(stringValue: "ruleSet")

    static let _knownKeys: Set<Swift.String> = [
      "infoTypes",
      "minLikelihood",
      "minLikelihoodPerInfoType",
      "limits",
      "includeQuote",
      "excludeInfoTypes",
      "customInfoTypes",
      "contentOptions",
      "ruleSet",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent([InfoType].self, forKey: .infoTypes) {
      self.infoTypes = value
    }
    if let value = try container.decodeIfPresent(Likelihood.self, forKey: .minLikelihood) {
      self.minLikelihood = value
    }
    if let value = try container.decodeIfPresent(
      [InspectConfig.InfoTypeLikelihood].self, forKey: .minLikelihoodPerInfoType)
    {
      self.minLikelihoodPerInfoType = value
    }
    self.limits = try container.decodeIfPresent(InspectConfig.FindingLimits.self, forKey: .limits)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .includeQuote) {
      self.includeQuote = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .excludeInfoTypes) {
      self.excludeInfoTypes = value
    }
    if let value = try container.decodeIfPresent([CustomInfoType].self, forKey: .customInfoTypes) {
      self.customInfoTypes = value
    }
    if let value = try container.decodeIfPresent([ContentOption].self, forKey: .contentOptions) {
      self.contentOptions = value
    }
    if let value = try container.decodeIfPresent([InspectionRuleSet].self, forKey: .ruleSet) {
      self.ruleSet = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.infoTypes, forKey: .infoTypes)
    try container.encode(self.minLikelihood, forKey: .minLikelihood)
    try container.encode(self.minLikelihoodPerInfoType, forKey: .minLikelihoodPerInfoType)
    try container.encodeIfPresent(self.limits, forKey: .limits)
    try container.encode(self.includeQuote, forKey: .includeQuote)
    try container.encode(self.excludeInfoTypes, forKey: .excludeInfoTypes)
    try container.encode(self.customInfoTypes, forKey: .customInfoTypes)
    try container.encode(self.contentOptions, forKey: .contentOptions)
    try container.encode(self.ruleSet, forKey: .ruleSet)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Configuration for setting a minimum likelihood per infotype. Used to
  /// customize the minimum likelihood level for specific infotypes in the
  /// request. For example, use this if you want to lower the precision for
  /// PERSON_NAME without lowering the precision for the other infotypes in the
  /// request.
  public struct InfoTypeLikelihood: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Type of information the likelihood threshold applies to. Only one
    /// likelihood per info_type should be provided. If InfoTypeLikelihood does
    /// not have an info_type, the configuration fails.
    public var infoType: InfoType? = nil

    /// Only returns findings equal to or above this threshold. This field is
    /// required or else the configuration fails.
    public var minLikelihood: Likelihood = Likelihood()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `InfoTypeLikelihood`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = InfoTypeLikelihood().with { $0.infoType = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let infoType = CodingKeys(stringValue: "infoType")
      static let minLikelihood = CodingKeys(stringValue: "minLikelihood")

      static let _knownKeys: Set<Swift.String> = [
        "infoType",
        "minLikelihood",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.infoType = try container.decodeIfPresent(InfoType.self, forKey: .infoType)
      if let value = try container.decodeIfPresent(Likelihood.self, forKey: .minLikelihood) {
        self.minLikelihood = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.infoType, forKey: .infoType)
      try container.encode(self.minLikelihood, forKey: .minLikelihood)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The type URL for `InfoTypeLikelihood`: `"type.googleapis.com/google.privacy.dlp.v2.InspectConfig.InfoTypeLikelihood"`.
    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.privacy.dlp.v2.InspectConfig.InfoTypeLikelihood"
    }

    /// Initialize an instance of `InfoTypeLikelihood` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.privacy.dlp.v2.InspectConfig.InfoTypeLikelihood"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `InfoTypeLikelihood` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Configuration to control the number of findings returned for inspection.
  /// This is not used for de-identification or data profiling.
  ///
  /// When redacting sensitive data from images, finding limits don't apply. They
  /// can cause unexpected or inconsistent results, where only some data is
  /// redacted. Don't include finding limits in
  /// [RedactImage][google.privacy.dlp.v2.DlpService.RedactImage]
  /// requests. Otherwise, Cloud DLP returns an error.
  ///
  /// [google.privacy.dlp.v2.DlpService.RedactImage]: <doc:DlpServiceClient/redactImage(request:options:)>
  public struct FindingLimits: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Max number of findings that are returned for each item scanned.
    ///
    /// When set within an
    /// [InspectContentRequest][google.privacy.dlp.v2.InspectContentRequest],
    /// this field is ignored.
    ///
    /// This value isn't a hard limit. If the number of findings for an item
    /// reaches this limit, the inspection of that item ends gradually, not
    /// abruptly. Therefore, the actual number of findings that Cloud DLP returns
    /// for the item can be multiple times higher than this value.
    ///
    /// [google.privacy.dlp.v2.InspectContentRequest]: <doc:InspectContentRequest>
    public var maxFindingsPerItem: Swift.Int32 = Swift.Int32()

    /// Max number of findings that are returned per request or job.
    ///
    /// If you set this field in an
    /// [InspectContentRequest][google.privacy.dlp.v2.InspectContentRequest], the
    /// resulting maximum value is the value that you set or 3,000, whichever is
    /// lower.
    ///
    /// This value isn't a hard limit. If an inspection reaches this limit, the
    /// inspection ends gradually, not abruptly. Therefore, the actual number of
    /// findings that Cloud DLP returns can be multiple times higher than this
    /// value.
    ///
    /// [google.privacy.dlp.v2.InspectContentRequest]: <doc:InspectContentRequest>
    public var maxFindingsPerRequest: Swift.Int32 = Swift.Int32()

    /// Configuration of findings limit given for specified infoTypes.
    public var maxFindingsPerInfoType: [InspectConfig.FindingLimits.InfoTypeLimit] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `FindingLimits`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = FindingLimits().with { $0.maxFindingsPerItem = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let maxFindingsPerItem = CodingKeys(stringValue: "maxFindingsPerItem")
      static let maxFindingsPerRequest = CodingKeys(stringValue: "maxFindingsPerRequest")
      static let maxFindingsPerInfoType = CodingKeys(stringValue: "maxFindingsPerInfoType")

      static let _knownKeys: Set<Swift.String> = [
        "maxFindingsPerItem",
        "maxFindingsPerRequest",
        "maxFindingsPerInfoType",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .maxFindingsPerItem) {
        self.maxFindingsPerItem = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .maxFindingsPerRequest)
      {
        self.maxFindingsPerRequest = value
      }
      if let value = try container.decodeIfPresent(
        [InspectConfig.FindingLimits.InfoTypeLimit].self, forKey: .maxFindingsPerInfoType)
      {
        self.maxFindingsPerInfoType = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.maxFindingsPerItem, forKey: .maxFindingsPerItem)
      try container.encode(self.maxFindingsPerRequest, forKey: .maxFindingsPerRequest)
      try container.encode(self.maxFindingsPerInfoType, forKey: .maxFindingsPerInfoType)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Max findings configuration per infoType, per content item or long
    /// running DlpJob.
    public struct InfoTypeLimit: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// Type of information the findings limit applies to. Only one limit per
      /// info_type should be provided. If InfoTypeLimit does not have an
      /// info_type, the DLP API applies the limit against all info_types that
      /// are found but not specified in another InfoTypeLimit.
      public var infoType: InfoType? = nil

      /// Max findings limit for the given infoType.
      public var maxFindings: Swift.Int32 = Swift.Int32()

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `InfoTypeLimit`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = InfoTypeLimit().with { $0.infoType = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let infoType = CodingKeys(stringValue: "infoType")
        static let maxFindings = CodingKeys(stringValue: "maxFindings")

        static let _knownKeys: Set<Swift.String> = [
          "infoType",
          "maxFindings",
        ]
      }

      public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.infoType = try container.decodeIfPresent(InfoType.self, forKey: .infoType)
        if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .maxFindings) {
          self.maxFindings = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(self.infoType, forKey: .infoType)
        try container.encode(self.maxFindings, forKey: .maxFindings)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      /// The type URL for `InfoTypeLimit`: `"type.googleapis.com/google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit"`.
      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit"
      }

      /// Initialize an instance of `InfoTypeLimit` by unpacking from a `GoogleWKT.WKTAny`.
      ///
      /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
      /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit"`,
      ///   or if deserialization fails.
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }

      /// Packs this `InfoTypeLimit` into a `GoogleWKT.WKTStruct` representation.
      ///
      /// - Throws: An error if serialization fails.
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    /// The type URL for `FindingLimits`: `"type.googleapis.com/google.privacy.dlp.v2.InspectConfig.FindingLimits"`.
    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.privacy.dlp.v2.InspectConfig.FindingLimits"
    }

    /// Initialize an instance of `FindingLimits` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.privacy.dlp.v2.InspectConfig.FindingLimits"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `FindingLimits` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The type URL for `InspectConfig`: `"type.googleapis.com/google.privacy.dlp.v2.InspectConfig"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.InspectConfig"
  }

  /// Initialize an instance of `InspectConfig` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.privacy.dlp.v2.InspectConfig"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `InspectConfig` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
