// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Configuration for a custom dictionary created from a data source of any size
/// up to the maximum size defined in the
/// [limits](https://docs.cloud.google.com/sensitive-data-protection/limits)
/// page. The artifacts of dictionary creation are stored in the specified Cloud
/// Storage location. Consider using `CustomInfoType.Dictionary` for smaller
/// dictionaries that satisfy the size requirements.
public struct LargeCustomDictionaryConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Location to store dictionary artifacts in Cloud Storage. These files
  /// will only be accessible by project owners and the DLP API. If any of these
  /// artifacts are modified, the dictionary is considered invalid and can no
  /// longer be used.
  public var outputPath: CloudStoragePath? = nil

  /// Source of the dictionary.
  public var source: SourceOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `LargeCustomDictionaryConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LargeCustomDictionaryConfig().with { $0.outputPath = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let outputPath = CodingKeys(stringValue: "outputPath")
    static let cloudStorageFileSet = CodingKeys(stringValue: "cloudStorageFileSet")
    static let bigQueryField = CodingKeys(stringValue: "bigQueryField")

    static let _knownKeys: Set<Swift.String> = [
      "outputPath",
      "cloudStorageFileSet",
      "bigQueryField",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.outputPath = try container.decodeIfPresent(CloudStoragePath.self, forKey: .outputPath)

    var source: SourceOneOf? = nil
    let sourceCheckAndSet = {
      if source != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'source'"))
      }
      source = $0
    }
    if let cloudStorageFileSet = try container.decodeIfPresent(
      CloudStorageFileSet.self, forKey: .cloudStorageFileSet)
    {
      try sourceCheckAndSet(.cloudStorageFileSet(cloudStorageFileSet))
    }
    if let bigQueryField = try container.decodeIfPresent(BigQueryField.self, forKey: .bigQueryField)
    {
      try sourceCheckAndSet(.bigQueryField(bigQueryField))
    }
    self.source = source
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.outputPath, forKey: .outputPath)

    if let choice = self.source {
      switch choice {
      case .cloudStorageFileSet(let value):
        try container.encode(value, forKey: .cloudStorageFileSet)
      case .bigQueryField(let value):
        try container.encode(value, forKey: .bigQueryField)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Source of the dictionary.
  public enum SourceOneOf: Codable, Equatable, Sendable {
    /// Set of files containing newline-delimited lists of dictionary phrases.
    indirect case cloudStorageFileSet(CloudStorageFileSet)
    /// Field in a BigQuery table where each cell represents a dictionary phrase.
    indirect case bigQueryField(BigQueryField)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.LargeCustomDictionaryConfig"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
