// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request message for ListInspectTemplates.
public struct ListInspectTemplatesRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Parent resource name.
  ///
  /// The format of this value varies depending on the scope of the request
  /// (project or organization) and whether you have [specified a processing
  /// location](https://docs.cloud.google.com/sensitive-data-protection/docs/specifying-location):
  ///
  /// + Projects scope, location specified:
  ///   `projects/{project_id}/locations/{location_id}`
  /// + Projects scope, no location specified (defaults to global):
  ///   `projects/{project_id}`
  /// + Organizations scope, location specified:
  ///   `organizations/{org_id}/locations/{location_id}`
  /// + Organizations scope, no location specified (defaults to global):
  ///   `organizations/{org_id}`
  ///
  /// The following example `parent` string specifies a parent project with the
  /// identifier `example-project`, and specifies the `europe-west3` location
  /// for processing data:
  ///
  ///     parent=projects/example-project/locations/europe-west3
  public var parent: Swift.String = Swift.String()

  /// Page token to continue retrieval. Comes from the previous call
  /// to `ListInspectTemplates`.
  public var pageToken: Swift.String = Swift.String()

  /// Size of the page. This value can be limited by the server. If zero server
  /// returns a page of max size 100.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Comma-separated list of fields to order by,
  /// followed by `asc` or `desc` postfix. This list is case insensitive. The
  /// default sorting order is ascending. Redundant space characters are
  /// insignificant.
  ///
  /// Example: `name asc,update_time, create_time desc`
  ///
  /// Supported fields are:
  ///
  /// - `create_time`: corresponds to the time the template was created.
  /// - `update_time`: corresponds to the time the template was last updated.
  /// - `name`: corresponds to the template's name.
  /// - `display_name`: corresponds to the template's display name.
  public var orderBy: Swift.String = Swift.String()

  /// Deprecated. This field has no effect.
  public var locationId: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ListInspectTemplatesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListInspectTemplatesRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let pageToken = CodingKeys(stringValue: "pageToken")
    static let pageSize = CodingKeys(stringValue: "pageSize")
    static let orderBy = CodingKeys(stringValue: "orderBy")
    static let locationId = CodingKeys(stringValue: "locationId")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "pageToken",
      "pageSize",
      "orderBy",
      "locationId",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .pageToken) {
      self.pageToken = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .pageSize) {
      self.pageSize = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .orderBy) {
      self.orderBy = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .locationId) {
      self.locationId = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.pageToken, forKey: .pageToken)
    try container.encode(self.pageSize, forKey: .pageSize)
    try container.encode(self.orderBy, forKey: .orderBy)
    try container.encode(self.locationId, forKey: .locationId)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.ListInspectTemplatesRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
