// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Specifies the location of the finding.
public struct Location: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Zero-based byte offsets delimiting the finding.
  /// These are relative to the finding's containing element.
  /// Note that when the content is not textual, this references
  /// the UTF-8 encoded textual representation of the content.
  /// Omitted if content is an image.
  public var byteRange: Range? = nil

  /// Unicode character offsets delimiting the finding.
  /// These are relative to the finding's containing element.
  /// Provided when the content is text.
  public var codepointRange: Range? = nil

  /// List of nested objects pointing to the precise location of the finding
  /// within the file or record.
  public var contentLocations: [ContentLocation] = []

  /// Information about the container where this finding occurred, if available.
  public var container: Container? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Location`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Location().with { $0.byteRange = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let byteRange = CodingKeys(stringValue: "byteRange")
    static let codepointRange = CodingKeys(stringValue: "codepointRange")
    static let contentLocations = CodingKeys(stringValue: "contentLocations")
    static let container = CodingKeys(stringValue: "container")

    static let _knownKeys: Set<Swift.String> = [
      "byteRange",
      "codepointRange",
      "contentLocations",
      "container",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.byteRange = try container.decodeIfPresent(Range.self, forKey: .byteRange)
    self.codepointRange = try container.decodeIfPresent(Range.self, forKey: .codepointRange)
    if let value = try container.decodeIfPresent([ContentLocation].self, forKey: .contentLocations)
    {
      self.contentLocations = value
    }
    self.container = try container.decodeIfPresent(Container.self, forKey: .container)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.byteRange, forKey: .byteRange)
    try container.encodeIfPresent(self.codepointRange, forKey: .codepointRange)
    try container.encode(self.contentLocations, forKey: .contentLocations)
    try container.encodeIfPresent(self.container, forKey: .container)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.Location"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
