// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Infotype details for other infoTypes found within a column.
public struct OtherInfoTypeSummary: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The other infoType.
  public var infoType: InfoType? = nil

  /// Approximate percentage of non-null rows that contained data detected by
  /// this infotype.
  public var estimatedPrevalence: Swift.Int32 = Swift.Int32()

  /// Whether this infoType was excluded from sensitivity and risk analysis due
  /// to factors such as low prevalence (subject to change).
  public var excludedFromAnalysis: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `OtherInfoTypeSummary`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = OtherInfoTypeSummary().with { $0.infoType = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let infoType = CodingKeys(stringValue: "infoType")
    static let estimatedPrevalence = CodingKeys(stringValue: "estimatedPrevalence")
    static let excludedFromAnalysis = CodingKeys(stringValue: "excludedFromAnalysis")

    static let _knownKeys: Set<Swift.String> = [
      "infoType",
      "estimatedPrevalence",
      "excludedFromAnalysis",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.infoType = try container.decodeIfPresent(InfoType.self, forKey: .infoType)
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .estimatedPrevalence) {
      self.estimatedPrevalence = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .excludedFromAnalysis) {
      self.excludedFromAnalysis = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.infoType, forKey: .infoType)
    try container.encode(self.estimatedPrevalence, forKey: .estimatedPrevalence)
    try container.encode(self.excludedFromAnalysis, forKey: .excludedFromAnalysis)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.OtherInfoTypeSummary"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
