// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The other cloud starting location for discovery.
public struct OtherCloudDiscoveryStartingLocation: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The other cloud starting location for discovery.
  public var location: LocationOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `OtherCloudDiscoveryStartingLocation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = OtherCloudDiscoveryStartingLocation().with { $0.awsLocation = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let awsLocation = CodingKeys(stringValue: "awsLocation")

    static let _knownKeys: Set<Swift.String> = [
      "awsLocation"
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var location: LocationOneOf? = nil
    let locationCheckAndSet = {
      if location != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'location'"))
      }
      location = $0
    }
    if let awsLocation = try container.decodeIfPresent(
      OtherCloudDiscoveryStartingLocation.AwsDiscoveryStartingLocation.self, forKey: .awsLocation)
    {
      try locationCheckAndSet(.awsLocation(awsLocation))
    }
    self.location = location
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.location {
      switch choice {
      case .awsLocation(let value):
        try container.encode(value, forKey: .awsLocation)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The AWS starting location for discovery.
  public struct AwsDiscoveryStartingLocation: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The scope of this starting location.
    public var scope: ScopeOneOf? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `AwsDiscoveryStartingLocation`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AwsDiscoveryStartingLocation().with { $0.accountId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let accountId = CodingKeys(stringValue: "accountId")
      static let allAssetInventoryAssets = CodingKeys(stringValue: "allAssetInventoryAssets")

      static let _knownKeys: Set<Swift.String> = [
        "accountId",
        "allAssetInventoryAssets",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var scope: ScopeOneOf? = nil
      let scopeCheckAndSet = {
        if scope != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'scope'"))
        }
        scope = $0
      }
      if let accountId = try container.decodeIfPresent(Swift.String.self, forKey: .accountId) {
        try scopeCheckAndSet(.accountId(accountId))
      }
      if let allAssetInventoryAssets = try container.decodeIfPresent(
        Swift.Bool.self, forKey: .allAssetInventoryAssets)
      {
        try scopeCheckAndSet(.allAssetInventoryAssets(allAssetInventoryAssets))
      }
      self.scope = scope
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.scope {
        switch choice {
        case .accountId(let value):
          try container.encode(value, forKey: .accountId)
        case .allAssetInventoryAssets(let value):
          try container.encode(value, forKey: .allAssetInventoryAssets)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The scope of this starting location.
    public enum ScopeOneOf: Codable, Equatable, Sendable {
      /// The AWS account ID that this discovery config applies to.
      /// Within an AWS organization, you can find the AWS account ID inside an
      /// AWS account ARN. Example:
      /// arn:{partition}:organizations::{management_account_id}:account/{org_id}/{account_id}
      case accountId(Swift.String)
      /// All AWS assets stored in Asset Inventory that didn't match other AWS
      /// discovery configs.
      case allAssetInventoryAssets(Swift.Bool)
    }

    /// The type URL for `AwsDiscoveryStartingLocation`: `"type.googleapis.com/google.privacy.dlp.v2.OtherCloudDiscoveryStartingLocation.AwsDiscoveryStartingLocation"`.
    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.privacy.dlp.v2.OtherCloudDiscoveryStartingLocation.AwsDiscoveryStartingLocation"
    }

    /// Initialize an instance of `AwsDiscoveryStartingLocation` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.privacy.dlp.v2.OtherCloudDiscoveryStartingLocation.AwsDiscoveryStartingLocation"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `AwsDiscoveryStartingLocation` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The other cloud starting location for discovery.
  public enum LocationOneOf: Codable, Equatable, Sendable {
    /// The AWS starting location for discovery.
    indirect case awsLocation(OtherCloudDiscoveryStartingLocation.AwsDiscoveryStartingLocation)
  }

  /// The type URL for `OtherCloudDiscoveryStartingLocation`: `"type.googleapis.com/google.privacy.dlp.v2.OtherCloudDiscoveryStartingLocation"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.OtherCloudDiscoveryStartingLocation"
  }

  /// Initialize an instance of `OtherCloudDiscoveryStartingLocation` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.privacy.dlp.v2.OtherCloudDiscoveryStartingLocation"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `OtherCloudDiscoveryStartingLocation` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
