// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Match resources using regex filters.
public struct OtherCloudResourceCollection: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The first filter containing a pattern that matches a resource will be used.
  public var pattern: PatternOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `OtherCloudResourceCollection`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = OtherCloudResourceCollection().with { $0.includeRegexes = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let includeRegexes = CodingKeys(stringValue: "includeRegexes")

    static let _knownKeys: Set<Swift.String> = [
      "includeRegexes"
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var pattern: PatternOneOf? = nil
    let patternCheckAndSet = {
      if pattern != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'pattern'"))
      }
      pattern = $0
    }
    if let includeRegexes = try container.decodeIfPresent(
      OtherCloudResourceRegexes.self, forKey: .includeRegexes)
    {
      try patternCheckAndSet(.includeRegexes(includeRegexes))
    }
    self.pattern = pattern
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.pattern {
      switch choice {
      case .includeRegexes(let value):
        try container.encode(value, forKey: .includeRegexes)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The first filter containing a pattern that matches a resource will be used.
  public enum PatternOneOf: Codable, Equatable, Sendable {
    /// A collection of regular expressions to match a resource against.
    indirect case includeRegexes(OtherCloudResourceRegexes)
  }

  /// The type URL for `OtherCloudResourceCollection`: `"type.googleapis.com/google.privacy.dlp.v2.OtherCloudResourceCollection"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.OtherCloudResourceCollection"
  }

  /// Initialize an instance of `OtherCloudResourceCollection` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.privacy.dlp.v2.OtherCloudResourceCollection"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `OtherCloudResourceCollection` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
