// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Cloud repository for storing output.
public struct OutputStorageConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Schema used for writing the findings for Inspect jobs. This field is only
  /// used for Inspect and must be unspecified for Risk jobs. Columns are derived
  /// from the `Finding` object. If appending to an existing table, any columns
  /// from the predefined schema that are missing will be added. No columns in
  /// the existing table will be deleted.
  ///
  /// If unspecified, then all available columns will be used for a new table or
  /// an (existing) table with no schema, and no changes will be made to an
  /// existing table that has a schema.
  /// Only for use with external storage.
  public var outputSchema: OutputStorageConfig.OutputSchema = OutputStorageConfig.OutputSchema()

  /// Output storage types.
  /// *
  public var type: TypeOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `OutputStorageConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = OutputStorageConfig().with { $0.table = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let table = CodingKeys(stringValue: "table")
    static let storagePath = CodingKeys(stringValue: "storagePath")
    static let outputSchema = CodingKeys(stringValue: "outputSchema")

    static let _knownKeys: Set<Swift.String> = [
      "table",
      "storagePath",
      "outputSchema",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      OutputStorageConfig.OutputSchema.self, forKey: .outputSchema)
    {
      self.outputSchema = value
    }

    var type: TypeOneOf? = nil
    let typeCheckAndSet = {
      if type != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'type'"
          ))
      }
      type = $0
    }
    if let table = try container.decodeIfPresent(BigQueryTable.self, forKey: .table) {
      try typeCheckAndSet(.table(table))
    }
    if let storagePath = try container.decodeIfPresent(CloudStoragePath.self, forKey: .storagePath)
    {
      try typeCheckAndSet(.storagePath(storagePath))
    }
    self.type = type
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.outputSchema, forKey: .outputSchema)

    if let choice = self.type {
      switch choice {
      case .table(let value):
        try container.encode(value, forKey: .table)
      case .storagePath(let value):
        try container.encode(value, forKey: .storagePath)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Predefined schemas for storing findings.
  /// Only for use with external storage.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum OutputSchema: Codable, Equatable, Hashable, Sendable {
    /// Unused.
    case unspecified
    /// Basic schema including only `info_type`, `quote`, `certainty`, and
    /// `timestamp`.
    case basicColumns
    /// Schema tailored to findings from scanning Cloud Storage.
    case gcsColumns
    /// Schema tailored to findings from scanning Google Datastore.
    case datastoreColumns
    /// Schema tailored to findings from scanning Google BigQuery.
    case bigQueryColumns
    /// Schema containing all columns.
    case allColumns
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .basicColumns: return 1
      case .gcsColumns: return 2
      case .datastoreColumns: return 3
      case .bigQueryColumns: return 4
      case .allColumns: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "OUTPUT_SCHEMA_UNSPECIFIED"
      case .basicColumns: return "BASIC_COLUMNS"
      case .gcsColumns: return "GCS_COLUMNS"
      case .datastoreColumns: return "DATASTORE_COLUMNS"
      case .bigQueryColumns: return "BIG_QUERY_COLUMNS"
      case .allColumns: return "ALL_COLUMNS"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:OutputSchema/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "OUTPUT_SCHEMA_UNSPECIFIED": self = .unspecified
      case "BASIC_COLUMNS": self = .basicColumns
      case "GCS_COLUMNS": self = .gcsColumns
      case "DATASTORE_COLUMNS": self = .datastoreColumns
      case "BIG_QUERY_COLUMNS": self = .bigQueryColumns
      case "ALL_COLUMNS": self = .allColumns
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:OutputSchema/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .basicColumns
      case 2: self = .gcsColumns
      case 3: self = .datastoreColumns
      case 4: self = .bigQueryColumns
      case 5: self = .allColumns
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("OUTPUT_SCHEMA_UNSPECIFIED")
      case .basicColumns: return try container.encode("BASIC_COLUMNS")
      case .gcsColumns: return try container.encode("GCS_COLUMNS")
      case .datastoreColumns: return try container.encode("DATASTORE_COLUMNS")
      case .bigQueryColumns: return try container.encode("BIG_QUERY_COLUMNS")
      case .allColumns: return try container.encode("ALL_COLUMNS")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Output storage types.
  /// *
  public enum TypeOneOf: Codable, Equatable, Sendable {
    /// Store findings in an existing table or a new table in an existing
    /// dataset. If table_id is not set a new one will be generated
    /// for you with the following format:
    /// dlp_googleapis_yyyy_mm_dd_[dlp_job_id]. Pacific time zone will be used
    /// for generating the date details.
    ///
    /// For Inspect, each column in an existing output table must have the same
    /// name, type, and mode of a field in the `Finding` object.
    ///
    /// For Risk, an existing output table should be the output of a previous
    /// Risk analysis job run on the same source table, with the same privacy
    /// metric and quasi-identifiers. Risk jobs that analyze the same table but
    /// compute a different privacy metric, or use different sets of
    /// quasi-identifiers, cannot store their results in the same table.
    indirect case table(BigQueryTable)
    /// Store findings in an existing Cloud Storage bucket. Files will be
    /// generated with the job ID and file part number as the filename and will
    /// contain findings in textproto format as
    /// [SaveToGcsFindingsOutput][google.privacy.dlp.v2.SaveToGcsFindingsOutput].
    /// The filename will follow the naming convention `<job_id>-<shard_number>`.
    /// Example: `my-job-id-2`.
    ///
    /// Supported for [Inspect jobs][google.privacy.dlp.v2.InspectJobConfig]. The
    /// bucket must not be the same as the bucket being inspected. If storing
    /// findings to Cloud Storage, the output schema field should not be set. If
    /// set, it will be ignored.
    ///
    /// [google.privacy.dlp.v2.InspectJobConfig]: <doc:InspectJobConfig>
    /// [google.privacy.dlp.v2.SaveToGcsFindingsOutput]: <doc:SaveToGcsFindingsOutput>
    indirect case storagePath(CloudStoragePath)
  }

  /// The type URL for `OutputStorageConfig`: `"type.googleapis.com/google.privacy.dlp.v2.OutputStorageConfig"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.OutputStorageConfig"
  }

  /// Initialize an instance of `OutputStorageConfig` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.privacy.dlp.v2.OutputStorageConfig"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `OutputStorageConfig` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
