// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request to search for potentially sensitive info in an image and redact it
/// by covering it with a colored rectangle.
public struct RedactImageRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Parent resource name.
  ///
  /// The format of this value varies depending on whether you have [specified a
  /// processing
  /// location](https://docs.cloud.google.com/sensitive-data-protection/docs/specifying-location):
  ///
  /// + Projects scope, location specified:
  ///   `projects/{project_id}/locations/{location_id}`
  /// + Projects scope, no location specified (defaults to global):
  ///   `projects/{project_id}`
  ///
  /// The following example `parent` string specifies a parent project with the
  /// identifier `example-project`, and specifies the `europe-west3` location
  /// for processing data:
  ///
  ///     parent=projects/example-project/locations/europe-west3
  public var parent: Swift.String = Swift.String()

  /// Deprecated. This field has no effect.
  public var locationId: Swift.String = Swift.String()

  /// Configuration for the inspector.
  public var inspectConfig: InspectConfig? = nil

  /// The configuration for specifying what content to redact from images.
  public var imageRedactionConfigs: [RedactImageRequest.ImageRedactionConfig] = []

  /// Whether the response should include findings along with the redacted
  /// image.
  public var includeFindings: Swift.Bool = Swift.Bool()

  /// The content must be PNG, JPEG, SVG or BMP.
  public var byteItem: ByteContentItem? = nil

  /// The full resource name of the inspection template to use. Settings in the
  /// main `inspect_config` field override the corresponding settings in this
  /// inspection template.
  ///
  /// The merge behavior is as follows:
  ///
  ///   - Singular field: The main field's value replaces the value of the
  ///   corresponding field in the template.
  ///   - Repeated fields: The field values are appended to the list defined in
  ///   the template.
  ///   - Sub-messages and groups: The fields are recursively merged.
  public var inspectTemplate: Swift.String = Swift.String()

  /// The full resource name of the de-identification template to use. Settings
  /// in the main `image_redaction_configs` field override the corresponding
  /// settings in this de-identification template. The request fails if the
  /// type of the template's deidentify_config is not image_transformations.
  public var deidentifyTemplate: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `RedactImageRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RedactImageRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let locationId = CodingKeys(stringValue: "locationId")
    static let inspectConfig = CodingKeys(stringValue: "inspectConfig")
    static let imageRedactionConfigs = CodingKeys(stringValue: "imageRedactionConfigs")
    static let includeFindings = CodingKeys(stringValue: "includeFindings")
    static let byteItem = CodingKeys(stringValue: "byteItem")
    static let inspectTemplate = CodingKeys(stringValue: "inspectTemplate")
    static let deidentifyTemplate = CodingKeys(stringValue: "deidentifyTemplate")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "locationId",
      "inspectConfig",
      "imageRedactionConfigs",
      "includeFindings",
      "byteItem",
      "inspectTemplate",
      "deidentifyTemplate",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .locationId) {
      self.locationId = value
    }
    self.inspectConfig = try container.decodeIfPresent(InspectConfig.self, forKey: .inspectConfig)
    if let value = try container.decodeIfPresent(
      [RedactImageRequest.ImageRedactionConfig].self, forKey: .imageRedactionConfigs)
    {
      self.imageRedactionConfigs = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .includeFindings) {
      self.includeFindings = value
    }
    self.byteItem = try container.decodeIfPresent(ByteContentItem.self, forKey: .byteItem)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .inspectTemplate) {
      self.inspectTemplate = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .deidentifyTemplate) {
      self.deidentifyTemplate = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.locationId, forKey: .locationId)
    try container.encodeIfPresent(self.inspectConfig, forKey: .inspectConfig)
    try container.encode(self.imageRedactionConfigs, forKey: .imageRedactionConfigs)
    try container.encode(self.includeFindings, forKey: .includeFindings)
    try container.encodeIfPresent(self.byteItem, forKey: .byteItem)
    try container.encode(self.inspectTemplate, forKey: .inspectTemplate)
    try container.encode(self.deidentifyTemplate, forKey: .deidentifyTemplate)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Configuration for determining how redaction of images should occur.
  public struct ImageRedactionConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The color to use when redacting content from an image. If not specified,
    /// the default is black.
    public var redactionColor: Color? = nil

    /// Type of information to redact from images.
    public var target: TargetOneOf? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ImageRedactionConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ImageRedactionConfig().with { $0.infoType = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let infoType = CodingKeys(stringValue: "infoType")
      static let redactAllText = CodingKeys(stringValue: "redactAllText")
      static let redactionColor = CodingKeys(stringValue: "redactionColor")

      static let _knownKeys: Set<Swift.String> = [
        "infoType",
        "redactAllText",
        "redactionColor",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.redactionColor = try container.decodeIfPresent(Color.self, forKey: .redactionColor)

      var target: TargetOneOf? = nil
      let targetCheckAndSet = {
        if target != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'target'"))
        }
        target = $0
      }
      if let infoType = try container.decodeIfPresent(InfoType.self, forKey: .infoType) {
        try targetCheckAndSet(.infoType(infoType))
      }
      if let redactAllText = try container.decodeIfPresent(Swift.Bool.self, forKey: .redactAllText)
      {
        try targetCheckAndSet(.redactAllText(redactAllText))
      }
      self.target = target
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.redactionColor, forKey: .redactionColor)

      if let choice = self.target {
        switch choice {
        case .infoType(let value):
          try container.encode(value, forKey: .infoType)
        case .redactAllText(let value):
          try container.encode(value, forKey: .redactAllText)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Type of information to redact from images.
    public enum TargetOneOf: Codable, Equatable, Sendable {
      /// Only one per info_type should be provided per request. If not
      /// specified, and redact_all_text is false, the DLP API will redact all
      /// text that it matches against all info_types that are found, but not
      /// specified in another ImageRedactionConfig.
      indirect case infoType(InfoType)
      /// If true, all text found in the image, regardless whether it matches an
      /// info_type, is redacted. Only one should be provided.
      case redactAllText(Swift.Bool)
    }

    /// The type URL for `ImageRedactionConfig`: `"type.googleapis.com/google.privacy.dlp.v2.RedactImageRequest.ImageRedactionConfig"`.
    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.privacy.dlp.v2.RedactImageRequest.ImageRedactionConfig"
    }

    /// Initialize an instance of `ImageRedactionConfig` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.privacy.dlp.v2.RedactImageRequest.ImageRedactionConfig"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `ImageRedactionConfig` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The type URL for `RedactImageRequest`: `"type.googleapis.com/google.privacy.dlp.v2.RedactImageRequest"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.RedactImageRequest"
  }

  /// Initialize an instance of `RedactImageRequest` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.privacy.dlp.v2.RedactImageRequest"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `RedactImageRequest` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
