// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Version of a StoredInfoType, including the configuration used to build it,
/// create timestamp, and current state.
public struct StoredInfoTypeVersion: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// StoredInfoType configuration.
  public var config: StoredInfoTypeConfig? = nil

  /// Output only. Create timestamp of the version. Read-only, determined by the
  /// system when the version is created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Stored info type version state. Read-only, updated by the
  /// system during dictionary creation.
  public var state: StoredInfoTypeState = StoredInfoTypeState()

  /// Output only. Errors that occurred when creating this storedInfoType
  /// version, or anomalies detected in the storedInfoType data that render it
  /// unusable. Only the five most recent errors will be displayed, with the most
  /// recent error appearing first.
  ///
  /// For example, some of the data for stored custom dictionaries is put in
  /// the user's Cloud Storage bucket, and if this data is modified or
  /// deleted by the user or another system, the dictionary becomes invalid.
  ///
  /// If any errors occur, fix the problem indicated by the error message and
  /// use the UpdateStoredInfoType API method to create another version of the
  /// storedInfoType to continue using it, reusing the same `config` if it was
  /// not the source of the error.
  public var errors: [Error] = []

  /// Output only. Statistics about this storedInfoType version.
  public var stats: StoredInfoTypeStats? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `StoredInfoTypeVersion`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = StoredInfoTypeVersion().with { $0.config = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let config = CodingKeys(stringValue: "config")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let state = CodingKeys(stringValue: "state")
    static let errors = CodingKeys(stringValue: "errors")
    static let stats = CodingKeys(stringValue: "stats")

    static let _knownKeys: Set<Swift.String> = [
      "config",
      "createTime",
      "state",
      "errors",
      "stats",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.config = try container.decodeIfPresent(StoredInfoTypeConfig.self, forKey: .config)
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    if let value = try container.decodeIfPresent(StoredInfoTypeState.self, forKey: .state) {
      self.state = value
    }
    if let value = try container.decodeIfPresent([Error].self, forKey: .errors) {
      self.errors = value
    }
    self.stats = try container.decodeIfPresent(StoredInfoTypeStats.self, forKey: .stats)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.config, forKey: .config)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.errors, forKey: .errors)
    try container.encodeIfPresent(self.stats, forKey: .stats)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.StoredInfoTypeVersion"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
