// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Configuration for stored infoTypes. All fields and subfield are provided
/// by the user. For more information, see
/// https://docs.cloud.google.com/sensitive-data-protection/docs/creating-custom-infotypes.
public struct StoredInfoTypeConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Display name of the StoredInfoType (max 256 characters).
  public var displayName: Swift.String = Swift.String()

  /// Description of the StoredInfoType (max 256 characters).
  public var description: Swift.String = Swift.String()

  /// Stored infotype types.
  public var type: TypeOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `StoredInfoTypeConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = StoredInfoTypeConfig().with { $0.displayName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let displayName = CodingKeys(stringValue: "displayName")
    static let description = CodingKeys(stringValue: "description")
    static let largeCustomDictionary = CodingKeys(stringValue: "largeCustomDictionary")
    static let dictionary = CodingKeys(stringValue: "dictionary")
    static let regex = CodingKeys(stringValue: "regex")

    static let _knownKeys: Set<Swift.String> = [
      "displayName",
      "description",
      "largeCustomDictionary",
      "dictionary",
      "regex",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }

    var type: TypeOneOf? = nil
    let typeCheckAndSet = {
      if type != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'type'"
          ))
      }
      type = $0
    }
    if let largeCustomDictionary = try container.decodeIfPresent(
      LargeCustomDictionaryConfig.self, forKey: .largeCustomDictionary)
    {
      try typeCheckAndSet(.largeCustomDictionary(largeCustomDictionary))
    }
    if let dictionary = try container.decodeIfPresent(
      CustomInfoType.Dictionary.self, forKey: .dictionary)
    {
      try typeCheckAndSet(.dictionary(dictionary))
    }
    if let regex = try container.decodeIfPresent(CustomInfoType.Regex.self, forKey: .regex) {
      try typeCheckAndSet(.regex(regex))
    }
    self.type = type
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.description, forKey: .description)

    if let choice = self.type {
      switch choice {
      case .largeCustomDictionary(let value):
        try container.encode(value, forKey: .largeCustomDictionary)
      case .dictionary(let value):
        try container.encode(value, forKey: .dictionary)
      case .regex(let value):
        try container.encode(value, forKey: .regex)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Stored infotype types.
  public enum TypeOneOf: Codable, Equatable, Sendable {
    /// StoredInfoType where findings are defined by a dictionary of phrases.
    indirect case largeCustomDictionary(LargeCustomDictionaryConfig)
    /// Store dictionary-based CustomInfoType.
    indirect case dictionary(CustomInfoType.Dictionary)
    /// Store regular expression-based StoredInfoType.
    indirect case regex(CustomInfoType.Regex)
  }

  /// The type URL for `StoredInfoTypeConfig`: `"type.googleapis.com/google.privacy.dlp.v2.StoredInfoTypeConfig"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.StoredInfoTypeConfig"
  }

  /// Initialize an instance of `StoredInfoTypeConfig` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.privacy.dlp.v2.StoredInfoTypeConfig"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `StoredInfoTypeConfig` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
