// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Specifies the location of a transformation.
public struct TransformationLocation: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Information about the functionality of the container where this finding
  /// occurred, if available.
  public var containerType: TransformationContainerType = TransformationContainerType()

  /// Location type.
  public var locationType: LocationTypeOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `TransformationLocation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TransformationLocation().with { $0.findingId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let findingId = CodingKeys(stringValue: "findingId")
    static let recordTransformation = CodingKeys(stringValue: "recordTransformation")
    static let containerType = CodingKeys(stringValue: "containerType")

    static let _knownKeys: Set<Swift.String> = [
      "findingId",
      "recordTransformation",
      "containerType",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      TransformationContainerType.self, forKey: .containerType)
    {
      self.containerType = value
    }

    var locationType: LocationTypeOneOf? = nil
    let locationTypeCheckAndSet = {
      if locationType != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'locationType'"))
      }
      locationType = $0
    }
    if let findingId = try container.decodeIfPresent(Swift.String.self, forKey: .findingId) {
      try locationTypeCheckAndSet(.findingId(findingId))
    }
    if let recordTransformation = try container.decodeIfPresent(
      RecordTransformation.self, forKey: .recordTransformation)
    {
      try locationTypeCheckAndSet(.recordTransformation(recordTransformation))
    }
    self.locationType = locationType
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.containerType, forKey: .containerType)

    if let choice = self.locationType {
      switch choice {
      case .findingId(let value):
        try container.encode(value, forKey: .findingId)
      case .recordTransformation(let value):
        try container.encode(value, forKey: .recordTransformation)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Location type.
  public enum LocationTypeOneOf: Codable, Equatable, Sendable {
    /// For infotype transformations, link to the corresponding findings ID so
    /// that location information does not need to be duplicated. Each findings
    /// ID correlates to an entry in the findings output table, this table only
    /// gets created when users specify to save findings (add the save findings
    /// action to the request).
    case findingId(Swift.String)
    /// For record transformations, provide a field and container information.
    indirect case recordTransformation(RecordTransformation)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.TransformationLocation"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
