// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// An enum of rules that can be used to transform a value. Can be a
/// record suppression, or one of the transformation rules specified under
/// `PrimitiveTransformation`.
///
/// - Note: Adding cases to this enumeration is not considered a breaking change.
///   Always include an `@unknown default:` case when switching over this type.
///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
///   expecting specific values to remain unparsed; future releases may promote
///   them to named cases.
public enum TransformationType: Codable, Equatable, Hashable, Sendable {
  /// Unused
  case unspecified
  /// Record suppression
  case recordSuppression
  /// Replace value
  case replaceValue
  /// Redact
  case redact
  /// Character mask
  case characterMask
  /// FFX-FPE
  case cryptoReplaceFfxFpe
  /// Fixed size bucketing
  case fixedSizeBucketing
  /// Bucketing
  case bucketing
  /// Replace with info type
  case replaceWithInfoType
  /// Time part
  case timePart
  /// Crypto hash
  case cryptoHash
  /// Date shift
  case dateShift
  /// Deterministic crypto
  case cryptoDeterministicConfig
  /// Redact image
  case redactImage
  /// Replace value using a dictionary.
  case replaceDictionary
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown value is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  ///
  /// - Warning: Do not pattern-match specific integer values in this case;
  ///   future releases may promote them to named enum cases.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown value is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  ///
  /// - Warning: Do not pattern-match specific string literals in this case;
  ///   future releases may promote them to named enum cases.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .recordSuppression: return 1
    case .replaceValue: return 2
    case .redact: return 3
    case .characterMask: return 4
    case .cryptoReplaceFfxFpe: return 5
    case .fixedSizeBucketing: return 6
    case .bucketing: return 7
    case .replaceWithInfoType: return 8
    case .timePart: return 9
    case .cryptoHash: return 10
    case .dateShift: return 12
    case .cryptoDeterministicConfig: return 13
    case .redactImage: return 14
    case .replaceDictionary: return 15
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "TRANSFORMATION_TYPE_UNSPECIFIED"
    case .recordSuppression: return "RECORD_SUPPRESSION"
    case .replaceValue: return "REPLACE_VALUE"
    case .redact: return "REDACT"
    case .characterMask: return "CHARACTER_MASK"
    case .cryptoReplaceFfxFpe: return "CRYPTO_REPLACE_FFX_FPE"
    case .fixedSizeBucketing: return "FIXED_SIZE_BUCKETING"
    case .bucketing: return "BUCKETING"
    case .replaceWithInfoType: return "REPLACE_WITH_INFO_TYPE"
    case .timePart: return "TIME_PART"
    case .cryptoHash: return "CRYPTO_HASH"
    case .dateShift: return "DATE_SHIFT"
    case .cryptoDeterministicConfig: return "CRYPTO_DETERMINISTIC_CONFIG"
    case .redactImage: return "REDACT_IMAGE"
    case .replaceDictionary: return "REPLACE_DICTIONARY"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:TransformationType/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "TRANSFORMATION_TYPE_UNSPECIFIED": self = .unspecified
    case "RECORD_SUPPRESSION": self = .recordSuppression
    case "REPLACE_VALUE": self = .replaceValue
    case "REPLACE_DICTIONARY": self = .replaceDictionary
    case "REDACT": self = .redact
    case "CHARACTER_MASK": self = .characterMask
    case "CRYPTO_REPLACE_FFX_FPE": self = .cryptoReplaceFfxFpe
    case "FIXED_SIZE_BUCKETING": self = .fixedSizeBucketing
    case "BUCKETING": self = .bucketing
    case "REPLACE_WITH_INFO_TYPE": self = .replaceWithInfoType
    case "TIME_PART": self = .timePart
    case "CRYPTO_HASH": self = .cryptoHash
    case "DATE_SHIFT": self = .dateShift
    case "CRYPTO_DETERMINISTIC_CONFIG": self = .cryptoDeterministicConfig
    case "REDACT_IMAGE": self = .redactImage
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:TransformationType/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .recordSuppression
    case 2: self = .replaceValue
    case 3: self = .redact
    case 4: self = .characterMask
    case 5: self = .cryptoReplaceFfxFpe
    case 6: self = .fixedSizeBucketing
    case 7: self = .bucketing
    case 8: self = .replaceWithInfoType
    case 9: self = .timePart
    case 10: self = .cryptoHash
    case 12: self = .dateShift
    case 13: self = .cryptoDeterministicConfig
    case 14: self = .redactImage
    case 15: self = .replaceDictionary
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode("TRANSFORMATION_TYPE_UNSPECIFIED")
    case .recordSuppression: return try container.encode("RECORD_SUPPRESSION")
    case .replaceValue: return try container.encode("REPLACE_VALUE")
    case .redact: return try container.encode("REDACT")
    case .characterMask: return try container.encode("CHARACTER_MASK")
    case .cryptoReplaceFfxFpe: return try container.encode("CRYPTO_REPLACE_FFX_FPE")
    case .fixedSizeBucketing: return try container.encode("FIXED_SIZE_BUCKETING")
    case .bucketing: return try container.encode("BUCKETING")
    case .replaceWithInfoType: return try container.encode("REPLACE_WITH_INFO_TYPE")
    case .timePart: return try container.encode("TIME_PART")
    case .cryptoHash: return try container.encode("CRYPTO_HASH")
    case .dateShift: return try container.encode("DATE_SHIFT")
    case .cryptoDeterministicConfig: return try container.encode("CRYPTO_DETERMINISTIC_CONFIG")
    case .redactImage: return try container.encode("REDACT_IMAGE")
    case .replaceDictionary: return try container.encode("REPLACE_DICTIONARY")
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
