// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A flattened description of a `PrimitiveTransformation` or
/// `RecordSuppression`.
public struct TransformationDescription: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The transformation type.
  public var type: TransformationType = TransformationType()

  /// A description of the transformation. This is empty for a
  /// RECORD_SUPPRESSION, or is the output of calling toString() on the
  /// `PrimitiveTransformation` protocol buffer message for any other type of
  /// transformation.
  public var description: Swift.String = Swift.String()

  /// A human-readable string representation of the `RecordCondition`
  /// corresponding to this transformation. Set if a `RecordCondition` was used
  /// to determine whether or not to apply this transformation.
  ///
  /// Examples:
  ///     * (age_field > 85)
  ///     * (age_field <= 18)
  ///     * (zip_field exists)
  ///     * (zip_field == 01234) && (city_field != "Springville")
  ///     * (zip_field == 01234) && (age_field <= 18) && (city_field exists)
  public var condition: Swift.String = Swift.String()

  /// Set if the transformation was limited to a specific `InfoType`.
  public var infoType: InfoType? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `TransformationDescription`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TransformationDescription().with { $0.type = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let type = CodingKeys(stringValue: "type")
    static let description = CodingKeys(stringValue: "description")
    static let condition = CodingKeys(stringValue: "condition")
    static let infoType = CodingKeys(stringValue: "infoType")

    static let _knownKeys: Set<Swift.String> = [
      "type",
      "description",
      "condition",
      "infoType",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(TransformationType.self, forKey: .type) {
      self.type = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .condition) {
      self.condition = value
    }
    self.infoType = try container.decodeIfPresent(InfoType.self, forKey: .infoType)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.type, forKey: .type)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.condition, forKey: .condition)
    try container.encodeIfPresent(self.infoType, forKey: .infoType)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.TransformationDescription"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
