// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleType
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Set of primitive values supported by the system.
/// Note that for the purposes of inspection or transformation, the number
/// of bytes considered to comprise a 'Value' is based on its representation
/// as a UTF-8 encoded string. For example, if 'integer_value' is set to
/// 123456789, the number of bytes would be counted as 9, even though an
/// int64 only holds up to 8 bytes of data.
public struct Value: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Value types
  public var type: TypeOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Value`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Value().with { $0.integerValue = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let integerValue = CodingKeys(stringValue: "integerValue")
    static let floatValue = CodingKeys(stringValue: "floatValue")
    static let stringValue = CodingKeys(stringValue: "stringValue")
    static let booleanValue = CodingKeys(stringValue: "booleanValue")
    static let timestampValue = CodingKeys(stringValue: "timestampValue")
    static let timeValue = CodingKeys(stringValue: "timeValue")
    static let dateValue = CodingKeys(stringValue: "dateValue")
    static let dayOfWeekValue = CodingKeys(stringValue: "dayOfWeekValue")

    static let _knownKeys: Set<Swift.String> = [
      "integerValue",
      "floatValue",
      "stringValue",
      "booleanValue",
      "timestampValue",
      "timeValue",
      "dateValue",
      "dayOfWeekValue",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var type: TypeOneOf? = nil
    let typeCheckAndSet = {
      if type != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'type'"
          ))
      }
      type = $0
    }
    if let integerValue = try container.decodeIfPresent(Swift.Int64.self, forKey: .integerValue) {
      try typeCheckAndSet(.integerValue(integerValue))
    }
    if let floatValue = try container.decodeIfPresent(Swift.Double.self, forKey: .floatValue) {
      try typeCheckAndSet(.floatValue(floatValue))
    }
    if let stringValue = try container.decodeIfPresent(Swift.String.self, forKey: .stringValue) {
      try typeCheckAndSet(.stringValue(stringValue))
    }
    if let booleanValue = try container.decodeIfPresent(Swift.Bool.self, forKey: .booleanValue) {
      try typeCheckAndSet(.booleanValue(booleanValue))
    }
    if let timestampValue = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .timestampValue)
    {
      try typeCheckAndSet(.timestampValue(timestampValue))
    }
    if let timeValue = try container.decodeIfPresent(GoogleType.TimeOfDay.self, forKey: .timeValue)
    {
      try typeCheckAndSet(.timeValue(timeValue))
    }
    if let dateValue = try container.decodeIfPresent(GoogleType.Date.self, forKey: .dateValue) {
      try typeCheckAndSet(.dateValue(dateValue))
    }
    if let dayOfWeekValue = try container.decodeIfPresent(
      GoogleType.DayOfWeek.self, forKey: .dayOfWeekValue)
    {
      try typeCheckAndSet(.dayOfWeekValue(dayOfWeekValue))
    }
    self.type = type
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.type {
      switch choice {
      case .integerValue(let value):
        try container.encode(value, forKey: .integerValue)
      case .floatValue(let value):
        try container.encode(value, forKey: .floatValue)
      case .stringValue(let value):
        try container.encode(value, forKey: .stringValue)
      case .booleanValue(let value):
        try container.encode(value, forKey: .booleanValue)
      case .timestampValue(let value):
        try container.encode(value, forKey: .timestampValue)
      case .timeValue(let value):
        try container.encode(value, forKey: .timeValue)
      case .dateValue(let value):
        try container.encode(value, forKey: .dateValue)
      case .dayOfWeekValue(let value):
        try container.encode(value, forKey: .dayOfWeekValue)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Value types
  public enum TypeOneOf: Codable, Equatable, Sendable {
    /// integer
    case integerValue(Swift.Int64)
    /// float
    case floatValue(Swift.Double)
    /// string
    case stringValue(Swift.String)
    /// boolean
    case booleanValue(Swift.Bool)
    /// timestamp
    indirect case timestampValue(GoogleWKT.WKTTimestamp)
    /// time of day
    indirect case timeValue(GoogleType.TimeOfDay)
    /// date
    indirect case dateValue(GoogleType.Date)
    /// day of week
    case dayOfWeekValue(GoogleType.DayOfWeek)
  }

  /// The type URL for `Value`: `"type.googleapis.com/google.privacy.dlp.v2.Value"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.Value"
  }

  /// Initialize an instance of `Value` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.privacy.dlp.v2.Value"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `Value` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
